setopt GLOB_COMPLETE

#  Uses 256-color
export TERM=xterm-256color

# Path to your oh-my-zsh installation.
export ZSH=/home/batumon/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="wezm"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
autoload zmv
plugins=(git emoji)

# User configuration

export SCALA_HOME=/opt/scala
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:$SCALA_HOME/bin:$HOME/.local/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias vimgo='vim -u ~/.vimrc.go'
alias astudio='sh /opt/android-studio/bin/studio.sh'

# Aliases declaration
alias masterbot="export ROS_MASTER_URI="http://192.168.1.130:11311" && export ROS_IP="$(hostname -I)""
alias connectbot="ssh bbauvsbc1@bbauv"
alias send2bot="sh /home/batumon/Projects/bbauv/src/vision/scripts/sync.sh jin"
alias lo='rostopic pub /led_strip std_msgs/Int8 9'
alias getbag="scp 'bbauvsbc1@bbauv:~/bags/$1' ~/Projects/bbauv/src/vision/bags"
alias syncbag="sh ~/Projects/bbauv/src/vision/bags/getbag.sh"
alias shutter="rosrun dynamic_reconfigure dynparam set /bot_camera/bot_camera shutter $1"
alias restartnav="ssh -t alex@nav 'sudo reboot'"
# Restart network manager
alias reconnect="sudo systemctl restart network-manager.service"
alias visionmake="cd ~/Projects/bbauv && catkin_make --pkg vision"
alias bbmake="cd ~/Projects/bbauv && catkin_make && cd -"
alias ktmux="killall tmux"

# ROS setup and functions
source /opt/ros/kinetic/setup.zsh
source /home/batumon/Projects/bbauv/devel/setup.zsh

function bag() {
    rosbag play -l $1
}

function track() {
    rosservice call /vision/detector "$1: True"
}

function untrack() {
    rosservice call /vision/detector "$1: False"
}



# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_COMPLETION_TRIGGER='`'

# Git
alias git="hub"
alias gpr="git pull --rebase"
alias gpom="git push origin master"
alias gs="git status -sb"
alias gh="git hist"
alias gf='git fetch'
alias gb='git branch'
alias ga='git add'
alias gc='git commit -m $1'
alias gca='git commit --amend'
alias grc='git rebase --continue'
alias grs='git rebase --skip'

# Python virtualenv
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

# Pandoc aliases
alias topdf="pandoc -s -V geometry:margin=1in -o $1 $2"

# Set path for frequently accessed directory 
setopt autocd
export CDPATH=$CDPATH:~/github/:~/Projects/bbauv/src/vision/src/vision/

# Setting Golang
export GOPATH=$HOME/.go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
gocd () { cd `go list -f '{{.Dir}}' $1` }

# Connect to NSCC
alias connscc='ssh a0112213@nus.nscc.sg'
