(function(){function v(a){a.data&&a.data.forEach(function(b){var c=g.getTabPropertiesByAppId(b.appId);c.currentState!==f.done&&oneMinuteSignup.MessageService.sendLog(c.appId,c.type,"Script running not in done state");c.setState(f.running);c.setTimeout(w);c.appLoginUrl=b.appLoginUrl||b.url;c.appName=b.appName;c.url=b.url;c.username=b.username;c.activeScript=b.script;if(a.type===e.ResetRequestScript)c.type=k.request,c.activeTriggerScript=oneMinuteSignup.AppService.getTriggerScript(k.request,b.username);
else if(a.type===e.ResetScript){c.type=k.change;var l=oneMinuteSignup.AppService.generatePassword(b.passwordPolicy);console.log(b.url,l);c.newPassword=l;c.activeTriggerScript=oneMinuteSignup.AppService.getTriggerScript(k.change,l)}else a.type===e.LogoutScript&&(c.type=k.logout,c.activeTriggerScript=oneMinuteSignup.AppService.getTriggerScript(k.logout));console.log("App: "+c.appId+" Clear cookies");b.url?g.createTabOrNavigate(c,function(a){}):r({error:Error("No "+b.scriptType+"url found on "+b.appName)},
c)})}function x(a){a=g.getTabPropertiesByAppId(a.appId);oneMinuteSignup.ExtensionProxyService.focusTabById(a.tabId)}function y(a){a&&(a.currentState===f.done?oneMinuteSignup.MessageService.sendLog(a.appId,a.type,"Script done but got UseInfoNeeded"):(a.clearTimeout(),a.setState(f.suspended),oneMinuteSignup.MessageService.sendUserInfoNeeded(a.appId,a.type)))}function z(a){a&&(a.clearTimeout(),a.currentState===f.done?oneMinuteSignup.MessageService.sendLog(a.appId,a.type,"Script running already in done state"):
(a.currentState===f.suspended&&oneMinuteSignup.ExtensionProxyService.focusTabById(n),a.setState(f.done),g.closeTab(a),oneMinuteSignup.MessageService.sendDone(a.appId,a.type),a.type===k.change&&A(a.appName,a.appId,a.appLoginUrl,a.username,a.newPassword)))}function r(a,b){b&&(b.currentState===f.done?oneMinuteSignup.MessageService.sendLog(b.appId,b.type,"Script done but got Error"):(b.setState(f.done),g.closeTab(b),a&&a.error&&(a.error.message=JSON.stringify({exception:a.error.message,loginUrl:b.appLoginUrl,
appName:b.appName,appId:b.appId,scriptType:b.type,url:b.url})),oneMinuteSignup.MessageService.sendError(a||{},b.appId,b.url,b.type)))}function B(a){a=g.getTabPropertiesByAppId(a.appId);g.closeTab(a)}function C(a,b){q=b;g.createTab({url:a.url},function(a){u=a;g.focusTabById(a)})}function D(a){oneMinuteSignup.ExtensionProxyService.focusTabById(q);oneMinuteSignup.MessageService.sendOauthToken(a.token,a.state);g.closeTab({tabId:u})}function A(a,b,c,l,e){a={url:c,formdata2:"",group:get_default_group(c)||
"(none)",name:a,username:l,password:e,notes:"",orig_username:l,orig_password:e};if(!lploggedin)return null;c=punycode.URLToASCII(a.url);var g=a.formdata2,h=a.name,f=a.group,k=a.username;e=a.password;var n=a.orig_username,r=a.orig_password;l=null!=g&&0<g.length?!0:!1;var m=issharedfolder(g_shares,f);if(!checkreadonly(m))return{error:gs("Sorry, this shared folder is read-only.")};var p=0==m?g_local_key:m.sharekey,d=createNewAcct(),t=lp_gettld_url(AES._utf8_encode(c));d.genpw=!1;d.name=h;d.group=f;d.url=
AES._utf8_encode(c);d.tld=t;d.unencryptedUsername=k;d.username=lpmenc(k,!0,p);d.password=lpmenc(e,!0,p);d.extra="";d.fav=0;d.autologin=0;d.never_autofill=0;d.pwprotect=0;d.aid="0";0!=m&&(d.sharefolderid=m.id,0==m.give&&(d.sharedfromaid=1));var q=f;m&&(q=f.substr(m.decsharename.length+1));d.fields=[];d.save_all=a.save_all?1:0;t=[];g=updateAndEncryptData(g,d.fields,t,d,p,{save_all:0,username:n,password:r,new_username:k,new_password:e,fromiframe:1});h="name="+en(lpenc(h,p))+"&grouping="+en(lpenc(q,p))+
"&data="+en(bin2hex(g))+"&extra="+en(lpenc("",p));h=h+"&extjs=1&localupdate=1"+(0==m?"":"&sharedfolderid="+en(m.id));d.newvalues=t;l?h+="&ref="+en(AES.url2hex(c)):(h=h+"&aid=0"+("&url="+en(AES.url2hex(c))),h=h+"&openid_url="+("&username="+en(crypto_btoa(d.username))),h+="&password="+en(crypto_btoa(d.password)),h+="&auto=1"+get_identity_param(),c=is_application(d),l=function(a,c){var d=a.responseXML.documentElement.getElementsByTagName("result")[0];d&&"added"===d.getAttribute("action")&&(d=d.getAttribute("aid"),
oneMinuteSignup.MessageService.sendSavedToVault(b,f,e,d))},lpMakeRequest(base_url+(c?"addapp.php":"show.php"),h,l,l,a))}function w(a){a.setState(f.done);g.closeTab(a);var b=Error("Script timeout"),b={error:{name:b.name,stack:b.stack,message:JSON.stringify({exception:"Script timeout",loginUrl:a.appLoginUrl,appName:a.appName,appId:a.appId,scriptType:a.type,url:a.url})},type:oneMinuteSignup.MessageType.Error,appId:"",scriptType:""};oneMinuteSignup.MessageService.sendError(b,a.appId,a.url,a.type)}var e=
oneMinuteSignup.MessageType,f=oneMinuteSignup.ScriptState,k=oneMinuteSignup.ScriptType,g=new oneMinuteSignup.TabService,n=null,u=null,q=null;oneMinuteSignup.ExtensionProxyService.onMessage(function(a,b,c){var f=g.getTabPropertiesByTabId(b);switch(a.type){case e.ResetRequestScript:case e.ResetScript:case e.LogoutScript:n=b;oneMinuteSignup.MessageService.tabId=b;v(a);c();break;case e.Done:console.log("DONE APP",f,b);z(f);c();break;case e.Error:r(a,f);c();break;case e.NavigateToTab:x(a);c();break;case e.UserInformationNeeded:y(f);
c();break;case e.GetToken:n=b;oneMinuteSignup.MessageService.tabId=b;oneMinuteSignup.MessageService.sendToken();c();break;case e.LaunchApplication:oneMinuteSignup.ExtensionProxyService.createTab(a.data.url,!0,function(){});c();break;case e.CloseTab:B(a);c();break;case e.GetOauthToken:n=b;oneMinuteSignup.MessageService.tabId=b;C(a,b);c();break;case e.ReceivedOauthToken:D(a),c()}});oneMinuteSignup.ExtensionProxyService.onUpdateTab(function(a,b){var c=g.getTabPropertiesByTabId(a);c&&(console.log("App: "+
c.appId+" Change url",b),c.currentState!==oneMinuteSignup.ScriptState.done&&(console.log("App: "+c.appId+" Execute script"),oneMinuteSignup.ExtensionProxyService.executeScriptWithFrameWork(c)))})})();
