LPTabState=function(){var h={};LPPlatform.onTabClosed(function(a){delete h[a]});Topics.get(Topics.CLEAR_DATA).subscribe(function(){h={}});var m=function(a,b){b=[].concat(b);var c=b.indexOf(lpmdec_acct(a.password,!0,a,g_shares));if(-1===c&&a.fields&&0<a.fields.length)for(var e=0;e<a.fields.length;++e){var g=a.fields[e];if("password"===g.type&&(c=b.indexOf(lpmdec_acct(g.value,!0,a,g_shares)),-1<c))break}return-1<c?b[c]:null},n=function(){var a=/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/g,
b=[function(c,a,b){if(1===a.uniquePasswords.length)return b=a.uniquePasswords[0],2===a.passwordsByValue[b].count&&(2===c.fields.length?c.passwordChangeForm=!0:c.createAccountForm=!0),b},function(c,a,b){for(var d in a.passwordsByValue)if(1<a.passwordsByValue[d].count)return 2===a.uniquePasswords.length?(c.passwordChangeForm=!0,c.originalPassword=a.uniquePasswords[0]===d?a.uniquePasswords[1]:a.uniquePasswords[0]):c.createAccountForm=!0,d},function(c,a,b){if(2===a.uniquePasswords.length){a:{b=b.getSites();
for(var d=a.uniquePasswords,e=0;e<b.length;++e){var l=m(b[e],d);if(l){b=l;break a}}b=null}if(b)return c.passwordChangeForm=!0,c.originalPassword=b,a.uniquePasswords[0]===b?a.uniquePasswords[1]:a.uniquePasswords[0]}},function(c,a,b){for(var d in a.passwordsByValue)if(c=a.passwordsByValue[d].field,b=["pw","pass"],g(c.attributes.name,b)||g(c.id,b))return d}],c=[function(c,a,b){if(1===a.uniqueTextValues.length)return b=a.uniqueTextValues[0],2===a.textFieldsByValue[b].count&&(c.createAccountForm=!0),b},
function(a,c,b){for(var d in c.textFieldsByValue)if(1<c.textFieldsByValue[d].count)return a.createAccountForm=!0,d},function(c,a,b){c=c.fields;for(a=1;a<c.length;++a)if("password"===c[a].type&&(b=c[a-1],"password"!==b.type))return b.value},function(c,a,b){for(var d in g_sites)if(-1<a.uniqueTextValues.indexOf(g_sites[d].unencryptedUsername))return g_sites[d].unencryptedUsername},function(c,b,e){c=[];for(var d in b.textFieldsByValue)(b=d.match(a))&&1===b.length&&c.push(d);if(1===c.length)return c[0]},
function(c,a,b){for(var d in a.textFieldsByValue)if(c=a.textFieldsByValue[d].field,g(c.attributes.name,"user")||g(c.id,"user"))return d}],e=function(){var c=function(c,a,b){var d=b[a];"undefined"===typeof d?b[a]={field:c,count:1}:++d.count};return function(a){var b={},d={},e={};a.fields.forEach(function(a){"password"===a.type?c(a,a.value,b):(c(a,a.value,d),c(a,a.type,e))});return{passwordsByValue:b,textFieldsByValue:d,textFieldsByType:e,uniqueTextValues:Object.keys(d),uniquePasswords:Object.keys(b)}}}(),
g=function(a,c){if(a){c=[].concat(c);for(var b=0;b<c.length;++b)if(-1<a.indexOf(c[b]))return!0}return!1},p=function(c,a,b,e){for(var d=null,g=0;g<e.length&&!(d=e[g](c,a,b));++g);return d};return function(a,d){d.fields=d.fields||[];var g=e(d),f=!1,l=!d.generatedPassword;d.username||(d.username=p(d,g,a,c));d.password||(d.password=d.generatedPassword?d.generatedPassword:p(d,g,a,b));var h=function(){if(d.username&&!d.createAccountForm)for(var a=0;a<d.fields.length;++a){var c=d.fields[a];if(c.value===
d.username)return c}return null}();this.submitted=function(a){"boolean"===typeof a&&(l=a);return l};this.succeeded=function(a){"boolean"===typeof a&&(f=a);return f};this.getUsernameField=function(){return h};this.getUsername=function(){return d.username};this.getPassword=function(){return d.password};this.getFormData=function(){return d};this.getFields=function(){return d.fields.slice()};this.getOriginalPassword=function(){return d.originalPassword};this.isChangePasswordForm=function(){return!0===
d.passwordChangeForm};this.isCreateAccountForm=function(){return!0===d.createAccountForm};this.isBasicAuthentication=function(){return!0===d.basicAuthentication};this.shouldSaveFields=function(){return!this.isChangePasswordForm()&&!this.isCreateAccountForm()}}}(),f=function(a){this.tabID=a.tabID;this.domain=lp_gettld_url(a.tabURL);this.sites=[];this.username=this.usernameField=this.acccountsVersion=null};f.prototype.getSites=function(){if(this.acccountsVersion!==g_local_accts_version){this.sites=
[];var a=getsites(this.domain),b;for(b in a)this.sites.push(g_sites[b]);this.acccountsVersion=g_local_accts_version}return this.sites};f.prototype.getFields=function(){var a=[];this.passwordForm&&(a=this.passwordForm.getFields());var b=this.getUsernameField();b&&b.value===this.getUsername()&&0===a.filter(function(a){return a.name===b.name&&a.value===b.value}).length&&a.unshift(b);return a};f.prototype.getUsernameField=function(){if(!this.usernameField)for(var a in h){var b=h[a];if(b.usernameField&&
compare_tlds(b.domain,this.domain)){this.usernameField=b.usernameField;break}}return this.usernameField};f.prototype.setUsernameField=function(a){a&&(this.usernameField=a)};f.prototype.setUsername=function(a){a&&(this.username=a)};f.prototype.getUsername=function(){!this.username&&this.passwordForm&&(this.username=this.passwordForm.getUsername());if(!this.username)for(var a in h){var b=h[a];if(b.username&&compare_tlds(b.domain,this.domain)){this.username=b.username;break}}return this.username};f.prototype.processPasswordSubmit=
function(a,b){this.passwordForm=new n(this,a);this.setUsernameField(this.passwordForm.getUsernameField());this.setUsername(this.passwordForm.getUsername());if(a.generatedPassword)this.generatedPassword=a.generatedPassword;else LPPlatform.once(LPPlatform.onTransition,function(a){a:{switch(a.transitionType){case "auto_subframe":case "manual_subframe":a=!1;break a}a=-1<a.transitionQualifiers.indexOf("from_address_bar")||-1<a.transitionQualifiers.indexOf("forward_back")}a&&this.clear()},this)};f.prototype.processTextSubmit=
function(a,b){this.getUsernameField()&&a.fields.unshift(this.getUsernameField());var c=new n(this,a);this.setUsernameField(c.getUsernameField());this.setUsername(c.getUsername())};f.prototype.getMatchingSites=function(){var a=function(a,b){if(b&&-1<b.indexOf("@")){var c=b.split("@");return 2===c.length&&a===c[0]}return!1},b=function(c,b){var e;(e=c===b||a(c,b)||a(b,c))||(e=-1<b.indexOf("*")||-1<b.indexOf(String.fromCharCode(8226))?c.length===b.length&&(c[0]===b[0]||c[c.length-1]===b[b.length-1]):
!1);return e};return function(){var a=this,e=a.getSites();if(a.getUsername())e=e.filter(function(c){a:{var e=a.getUsername();if(b(c.unencryptedUsername,e))c=!0;else{if(c.fields&&0<c.fields.length)for(var d=0;d<c.fields.length;++d){var g=c.fields[d];switch(g.type){case "text":case "email":case "tel":if(b(lpmdec_acct(g.value,!0,c,g_shares),e)){c=!0;break a}}}c=!1}}return c});else{var g=a.passwordForm&&a.passwordForm.getOriginalPassword();g&&(e=e.filter(function(a){return null!==m(a,g)}));0===e.length&&
(e=a.getSites())}return e}}();f.prototype.shouldShowSiteNotification=function(){if(this.passwordForm&&this.passwordForm.succeeded())return this.passwordForm.isChangePasswordForm()?Preferences.get("showChangeNotificationBar"):Preferences.get("showSaveNotificationBar")};var r=function(){var a=function(a){var c="";a.forEach(function(a){c+=a.formname+"\t"+encodeURIComponent(a.name)+"\t"+encodeURIComponent(crypto_btoa(a.value))+"\t"+encodeURIComponent(a.type)+"\n"});return bin2hex(c)};return function(b,
c){b.fields=b.fields.concat(c);g_local_accts_version++;rewritelocalfile();var e={data:a(c),ref:url2hex(b.url),updatefields:1,aid:b.aid};b.sharedfolderid&&(e.sharedfolderid=b.sharedfolderid);b.postdata=(new PostParams(e)).toString();b.posturl=base_url+"gm_deliver.php";b.newvalues=c;updateFieldsFromSubmit(b.postdata,b)}}();f.prototype.addFields=function(a){if(this.getUsername()){var b=this.getFields();a.forEach(function(a){if(a.fields){var c=[];b.forEach(function(b){0===a.fields.filter(function(a){return a.name===
b.name&&a.formname===b.formname}).length&&c.push({otherfield:a.save_all,name:b.attributes.name||b.id,type:b.type,value:lpmenc_acct(b.value,!0,a,g_shares),checked:!1,formname:a.save_all?b.formname:"",urid:"0",otherlogin:"0",url:""})});r(a,c)}})}};f.prototype.getSiteNotificationData=function(a){if(this.passwordForm){var b={formSubmitted:this.passwordForm.submitted(),formSucceeded:this.passwordForm.succeeded()};if(this.shouldShowSiteNotification()){var c=this.passwordForm.getFormData(),e=this.getMatchingSites(),
g=e.filter(function(a){return null!==m(a,this.passwordForm.getPassword())},this);if(0<g.length)return this.addFields(g),this.clear({force:!0}),{};b.matchingSites=e.map(function(a){return a.aid});b.defaultData={url:this.passwordForm.shouldSaveFields()?c.url:hostof(c.url),name:this.domain,unencryptedUsername:this.getUsername(),group:siteCats[this.domain],basic_auth:this.passwordForm.isBasicAuthentication()?"1":"0",realm:c.realm};b.dialogData={password:this.passwordForm.getPassword()};b.sameDomain=compare_tlds(lp_gettld_url(this.passwordForm.getFormData().url),
lp_gettld_url(a.tabURL));b.generatedPassword=this.generatedPassword===this.passwordForm.getPassword();this.passwordForm.shouldSaveFields()&&0<this.getFields().length&&(b.dialogData.fields=this.getFields().map(function(a){return{name:a.attributes.name||a.id,type:a.type,value:a.value,formname:""}}))}else this.clear();return b}return{}};f.prototype.getFormSubmissionTabState=function(){for(var a=this;a;){if(a.passwordForm)return a;a=a.previousTabState}return this};f.prototype.getUsernames=function(){return this.getSites().map(function(a){return a.unencryptedUsername})};
f.prototype.getSiteNotification=function(){var a=function(a,b,g){var c=a.getUsernames();b.forEachWindow({each:function(b,d){return b.LPContentScriptTools.findText({searches:c,callback:function(b){a.setUsername(b);d()}})},done:g})},b=function(b,e,g){var c=!1,f=LPTabs.get({tabID:b.tabID}),d=function(){if(b.passwordForm&&(b.passwordForm.succeeded()||b.passwordForm.succeeded(!c),b.passwordForm.succeeded()&&!b.passwordForm.getUsername()&&0<b.getSites().length)){a(b,f,g);return}g()};e?(e=f.getFrame(e.frameID))&&
e.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=a;d()}):b.passwordForm.getFormData().top?f.getTop().LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=a;d()}):f.forEachFrame({each:function(a,d){return a.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){c=c||a;d()})},done:d})};return function(a,e){if(a.callback){var c=this.getFormSubmissionTabState(),f=function(){a.callback(c.getSiteNotificationData(e))};if(c.passwordForm&&c.passwordForm.getPassword())if(c.domain!==
this.domain||c.passwordForm.isBasicAuthentication())c.passwordForm.succeeded(!0);else{b(c,a.source,f);return}f()}}}();f.prototype.clear=function(a){var b=a&&a.force,c=!0;this.previousTabState&&(c=this.previousTabState.clear(a))&&delete this.previousTabState;this.passwordForm&&(this.passwordForm.getPassword()===this.generatedPassword&&(this.passwordForm.submitted(!1),c=!1),c||b)&&(delete this.passwordForm,delete this.generatedPassword);return c};f.prototype.processBasicAuthentication=function(a){this.passwordForm=
new n(this,{basicAuthentication:!0,url:a.url,realm:a.realm,username:a.username,password:a.password})};var q=function(a){if(!lploggedin)return!1;var b=lp_gettld_url(a.tabURL);if(LPContentScriptFeatures.new_save_site)return!hasNeverSave(a.tabURL,b)&&!lp_url_is_lastpass(a.tabURL)&&!lp_url_is_lastpassext(a.tabURL);a=IntroTutorial.getState();return a.enabled&&a.domain===b},k=function(a,b){if(a){if(q(a)){var c=h[a.tabID];if(!c||!compare_tlds(c.domain,lp_gettld_url(a.tabURL))){var e=h[a.tabID]=new f(a);
e.previousTabState=c;c=e}b(c)}}else LPPlatform.getCurrentTab(function(a){k(a.tabDetails,b)})};return{getSiteNotification:function(a,b){k(b,function(c){c.getSiteNotification(a,b)})},clear:function(a,b){k(b,function(b){b.clear(a)})},processPasswordSubmit:function(a,b){k(b,function(c){c.processPasswordSubmit(a.formData,b);c.getSiteNotification({callback:a.callback,source:b},b)})},processTextSubmit:function(a,b){k(b,function(c){c.processTextSubmit(a,b)})},processBasicAuthentication:function(a,b){k(b,
function(b){b.processBasicAuthentication(a)})},getState:function(a,b){var c={enabled:q(b)};c.enabled?k(b,function(b){c.usernames=b.getUsernames();a(c)}):a(c)}}}();
