(function(a){a.getBackgroundInterface=function(){var a=null;return function(g){null===a&&(g=g||{},g.source=window,g.direct=!0,a=Interfaces.createInstance(Interfaces.BackgroundInterface,g));return a}}()})(LPPlatform);
(function(a,k){a.getFavicon=function(c){c.callback&&c.callback(null)};a.once=function(c,a,d){if(c)var e=c(function(){e();a.apply(d,arguments)})};a.getBigIcons=function(c,a){var d=(a||"big")+"icons",e=opendb();createDataTable(e);if(e){var f=function(b,a){c(0<a.rows.length&&null!==a.rows.item(0).data?a.rows.item(0).data:"")};if(g_indexeddb){var h={rows:{item:function(b){return this[b]},length:0}};e.transaction("LastPassData","readonly").objectStore("LastPassData").openCursor(IDBKeyRange.only(db_prepend(g_username_hash)+
"_"+d)).onsuccess=function(b){(b=b.target.result)?(h.rows[h.rows.length]=b.value,h.rows.length++,b["continue"]()):f(null,h)}}else e.transaction(function(b){b.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),d],f,function(b,c){console_log(c)})})}};a.saveBigIcons=function(c,a){var d=(a||"big")+"icons",e=opendb();createDataTable(e);e&&(g_indexeddb?e.transaction("LastPassData","readwrite").objectStore("LastPassData").put({username_hash:db_prepend(g_username_hash),
type:d,data:c,usertype:db_prepend(g_username_hash)+"_"+d}):e.transaction(function(a){a.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),d,c],function(c,b){console_log("server.js : inserted")},function(c,b){console_log(b)})}))};a.updateBigIcons=function(){};var g=function(c,a){for(var d in c){var e=a[d];e&&(e.group=c[d])}};a.refreshGroupNames=function(c){c&&(g(c.sites,g_sites),g(c.notes,g_securenotes),g(c.applications,g_applications))};
a.useDialogWindows=function(){return Preferences.get("htmlindialog")};(function(){var c={},n=function(c,a){return function(){c.apply(this,arguments);a.apply(this,arguments)}};a.openTabDialog=function(d,e){var f={createAccountSimple:!0,siteTutorial:!0},h=d+(e?"-"+JSON.stringify(e):""),b=c[h];if(b)b.activate();else{var p={dialogWindow:a.useDialogWindows()&&!(e&&e.virtualKeyboard)},b={url:getchromeurl("tabDialog.html?dialog="+d),loadHandler:function(b){b.getTop().LPTabDialog.openDialog(d,e,p);c[h]=b},
closeHandler:function(){delete c[h]},tabId:e&&e.tabId?e.tabId:void 0};if(b.tabId)a.navigateTab(b);else if(p.dialogWindow&&!f[d]){var g=Preferences.get("dialogSizePrefs"),f=g[d];b.features={height:f?f.height:600,width:f?f.width:800,left:f?f.left:0,top:f?f.top:0};b.features.width>window.screen.availWidth&&(b.features.width=window.screen.availWidth,b.features.left=0);b.features.height>window.screen.availHeight&&(b.features.height=window.screen.availHeight,b.features.top=0);b.closeHandler=n(b.closeHandler,
function(b){g[d]={height:b.outerHeight,width:b.outerWidth,left:b.screenLeft||b.screenX,top:b.screenTop||b.screenY};Preferences.set("dialogSizePrefs",g);delete c[h]});a.openDialogWindow(b)}else if(f[d])a.openTab(b);else switch(Preferences.get("openpref")){case "tabs":a.openTab(b);break;case "windows":a.openWindow(b);break;case "same":a.openSame(b)}}}})();a.stringifyFeatures=function(c){var a=[],d;for(d in c)a.push(d+"="+c[d]);return a.join(",")};a.doAjax=function(a){LPServer.ajax(a)};a.ajax=function(c){isOffline()?
c.error&&c.error(null,null,"offline"):a.doAjax(c)};a.isEdge=function(){return is_edge()};a.copyDataIfEdge=function(c){return a.isEdge()&&"undefined"!==typeof c?JSON.parse(JSON.stringify(c)):c};a.setUserPreference=function(a){return function(c,d){a(c,d);g_userprefs_changed[c]=d}}(a.setUserPreference);a.setGlobalPreference=function(a){return function(c,d){a(c,d);g_gblprefs_changed[c]=d}}(a.setGlobalPreference);a.writePreferences=function(){lpWriteAllPrefs()};a.closePopovers=function(){};(function(){var c=
{},g={},d={},e={};k.LPTabs={get:function(a){if(a["interface"]){var c=[],b;for(b in e)e[b].tabDetails.interfaceName===a["interface"]&&c.push(e[b]);return c}if("undefined"!==typeof a.tabID){if(c=e[a.tabID])return a.callback&&a.callback(c),c;a.callback&&((c=d[a.tabID])||(c=d[a.tabID]=[]),c.push(a.callback))}}};a.initializeRequestFramework=function(a){var h=e[a.tabID],b={tabURL:a.tabURL,tabID:a.tabID,windowID:a.windowID},f=LPMessaging.getNewMessageSourceID(),l=!1,m=function(b){try{return b.frameID=f,
a.sendContentScript(b)}catch(u){return!1}},k=function(a){return m({type:"backgroundResponse",data:a})},n=function(d){(l=d.top)&&"undefined"!==typeof b.tabID&&(g[b.tabID]=f);m({type:"initialization",data:{tabID:b.tabID,frameID:f,topFrameID:g[b.tabID],request:d}});if(d.extendFrame){var t=c[f];c[d.extendFrame]=function(a){contentScriptSender(a);t(a)}}else c[f]=m;if(d.interfaceName&&Interfaces.hasOwnProperty(d.interfaceName)){b.interfaceName||(b.interfaceName=d.interfaceName);var q=function(a){return LPMessaging.makeRequest(m,
{type:"contentScriptRequest",sourceFrameID:0,data:a})},k=Interfaces.createInstance(Interfaces[d.interfaceName],{instance:d.extendFrame?h.getTop():null,direct:!1,context:a.context||"background",requestFunction:q});"number"!==typeof b.tabID&&!b.tabID||d.interfaceName!==b.interfaceName||d.extendFrame||(h||(h=e[b.tabID]=new LPTab(b)),h.addFrame(k,{topWindow:l,frameID:f,contentScriptRequester:q}));a.callback&&a.callback(k)}},r=function(){delete c[f];var a=e[b.tabID];a&&(a.removeFrame(f),a.isEmpty()&&(delete e[b.tabID],
delete g[b.tabID]))};return{frameID:f,requestHandler:function(a){switch(a.type){case "backgroundRequest":LPMessaging.handleRequest(Interfaces.BackgroundInterface,a.data,k,{additionalArguments:{tabURL:b.tabURL,tabID:b.tabID,windowID:b.windowID,frameID:f,top:l}});break;case "contentScriptRequest":case "contentScriptResponse":if(0===a.frameID)LPMessaging.handleResponse(a.data);else if(a.frameID){var e=c[a.frameID];e&&e(a)}break;case "initialize":n(a.data);break;case "disconnect":r();break;case "initialized":l&&
d[b.tabID]&&(d[b.tabID].forEach(function(a){a(h)}),delete d[b.tabID])}},disconnectHandler:r}}})()})(LPPlatform,this);
