LPSiteNotification=function(){var n=!1,w=!1,y=function(b){b.generatedPassword||(n=!0);bg.LPTabState.processPasswordSubmit({formData:b,callback:b.generatedPassword||LPContentScriptTools.isUnloading()?null:x})},v=function(){var b=function(c){return $(c||document.body).find('input:not([type]),input[type="text"],input[type="email"],input[type="password"]').filter(function(){return this.value&&LPContentScriptTools.isVisible(this)})},f=function(){var c=["submit","click","keydown"],k={},b=!1;return function(a,
d){-1<c.indexOf(a)?(k[a]=d,b||(b=!0,setTimeout(function(){for(var a=0;a<c.length;++a){var d=c[a];if(k.hasOwnProperty(d)){k[d]();break}}b=!1;k={}},0))):d()}}(),a=function(c){for(var k=[],b={},a={},d=0;d<c.length;++d){var e=c[d];switch(e.type){case "hidden":case "text":case "email":!e.value||"hidden"!==e.type&&LPContentScriptTools.isVisible(e)||(b.hasOwnProperty(e.value)?delete a[e.value]:(a[e.value]=e,b[e.value]=!0))}}var f={};LPContentScriptTools.findTextNodes({searches:Object.keys(a),searchAll:!0,
exactMatch:!0}).filter(function(g){return f.hasOwnProperty(g.match)?!1:f[g.match]=!0}).forEach(function(g){g.parent&&"OPTION"!==g.parent.nodeName&&LPContentScriptTools.isVisible(g.parent)&&k.push(a[g.match])});return k},d=function(c){for(var a=c.type,b=c.value,d=c.id,e=["name","ng-model","data-reactid"],f={},l=0;l<e.length;++l){var g=c.getAttribute(e[l]);g&&(f[e[l]]=g)}a={type:a,value:b,id:d,attributes:f};"password"!==a.type&&"disc"===$(c).css("text-security")&&(a.type="password");return a},e=function(c,
a){for(var b=[],d=0;d<c.length;++d){var e=c[d];"password"!==e.inputData.type&&(e.inputData.value=u.getUnmaskedValue({input:e.input,inputValue:e.inputData.value,form:a.form}));e.inputData.formname=a.form&&a.form.getAttribute("name")||"";b.push(e.inputData)}return{url:document.location.href,top:window===top,fields:b,generatedPassword:a.generatedPassword,username:u.getUsername()}};return function(c){var k=b(c.form);c.form&&(k=a(c.form).concat(k.toArray()));for(var m=[],h=!1,p=0;p<k.length;++p){var t=
k[p],l=d(t);"password"===l.type&&(h=!0);m.push({input:t,inputData:l})}if(c.deferred)return e(m,c);f(c.type,function(){var g=e(m,c);h?y(g):(0<k.length&&bg.LPTabState.processTextSubmit(g),bg.LPTabState.clear())})}}(),A=function(){var b=function(a){var b;if(a.id)b=$(document.getElementById(a.id));else for(var c in a.attributes)if(b=$("input["+c+'="'+a.attributes[c]+'"]'),0<b.length)break;return b},f=function(a,e){for(var c=0;c<a.fields.length;++c){var d=a.fields[c];if("password"===d.type){var c=d,d=
a,f=e,h=b(c);h&&0<h.length&&LPContentScriptTools.isVisible(h)?f&&!LPContentScriptTools.isClickable(h)?(w=!0,c=!1):c=n&&d.passwordChangeForm?h.val()===c.value:!0:c=!1;return c}}return!1},a=function(){var a=function(a,c){var d=b(a);d&&d.unbind("input.submissionFailed").bind("input.submissionFailed",function(){c(!0)})};return function(b,c){for(var d=0;d<b.fields.length;++d){var e=b.fields[d];"password"===e.type&&a(e,c)}}}();return function(b,e){var c=0,d=null,m=!1,h=function(a){m||(n=!1,m=!0,clearInterval(d),
e(a))};n?(d=setInterval(function(){++c;var a=5===c,d=f(b,a);d&&!a||h(d)},1E3),a(b,h)):h(f(b))}}(),x=function(b){LPContentScriptTools.isUnloading()||(Topics.get(Topics.SITE_NOTIFICATION_STATE).publish(b),bg.get("LPContentScriptFeatures").new_save_site&&b.dialogData&&!w&&csTop.LPSiteNotification.showSiteNotification(b))},z=function(){var b=function(a){a=a.toLowerCase();return-1<a.indexOf("submit")||-1<a.indexOf("save")},f=function(a){a=a.attributes;for(var d=0;d<a.length;++d){var e=a[d];if(b(e.name)||
b(e.value))return!0}return!1};return function(a){if("INPUT"===a.nodeName)return"submit"===a.type?!0:"button"===a.type?f(a):!1;for(;a&&0===a.getElementsByTagName("input").length;){if("BUTTON"===a.nodeName)return"submit"===a.type||f(a);if(f(a))return!0;a=a.parentElement}return!1}}(),q=function(){var b=null,f=[],a=function(){b&&(b.disconnect(),b=null);f=[]},d=function(a){for(var b=0;b<a.length;++b){var c=a[b];switch(c.type){case "attributes":if(c.target.getAttribute(c.attributeName)!==c.oldValue)return!0;
break;default:return!0}}return!1},e=function(b){d(b)&&(f.forEach(function(a){a()}),a())};return{reset:a,onChange:function(c){"function"===typeof MutationObserver&&(b||(b=new MutationObserver(e),b.observe(document.body,{childList:!0,attributes:!0,characterData:!0,subtree:!0,attributeOldValue:!0})),-1===f.indexOf(c)&&f.push(c),setTimeout(function(){a()},0))}}}(),r=function(){var b=null,f=null,a=function(a){return function(b){a(b.detail)}},d=function(){b&&window.removeEventListener("lprequeststart",
b)},e=function(){f&&window.removeEventListener("lprequestend",f)};return{onStart:function(c){d();b=a(c);window.addEventListener("lprequeststart",b)},onEnd:function(b){e();f=a(b);window.addEventListener("lprequestend",f)},reset:function(){d();e()}}}(),u=function(){var b=null,f=!1,a=!1,d=[];Topics.get(Topics.FILLED_GENERATED_PW).subscribe(function(a){c({target:a.element,generatedPassword:a.password})});Topics.get(Topics.CLEAR_DATA).subscribe(function(a){t()});Topics.get(Topics.LOGIN).subscribe(function(a){bg.LPTabState.getState(function(a){a.enabled&&
p(a)})});var e=function(a){return function(b){if(!1!==b.isTrusted)try{a(b)}catch(B){console.log(B)}}},c=function(a){a.form=LPContentScriptTools.getForm(a.target);return v(a)},k=function(){n=!1;bg.LPTabState.clear()},m=function(){var a=function(a){for(var b=0;b<a.fields.length;++b)if("password"===a.fields[b].type)return a.fields[b].value;return null};return function(b){var g=c({target:b,deferred:!0});if(g&&0<g.fields.length){var d=a(g);r.onStart(function(a){a&&a.data&&-1<a.data.indexOf(d)&&(r.reset(),
y(g))})}}}(),h={submit:function(a){q.reset();r.reset();v({form:LPContentScriptTools.getForm(a.target),type:a.type})},lpsubmit:function(a){q.reset();r.reset();v({form:a.target,type:"submit"})},click:e(function(a){var b=a.target;r.reset();if(z(b))q.reset(),c({target:b,type:a.type});else{if(n)q.onChange(k);m(b)}}),keydown:e(function(a){r.reset();if(13===(a.keyCode||a.which)){var b=a.target;if("INPUT"===b.nodeName||z(b))q.reset(),c({target:b,type:a.type});else{if(n)q.onChange(k);m(b)}}}),change:e(function(a){a=
a.target;if("INPUT"===a.nodeName&&a.value)switch(a.type){case "text":case "email":for(var b=0;b<d.length;++b)if(d[b].input===a){d[b].value=a.value;return}d.push({input:a,value:a.value})}})},p=function(c){b=c;f||(f=!0,c=document.createElement("script"),c.type="text/javascript",c.src=bg.get("extensionBaseURL")+"xhrExtension.js",document.head.appendChild(c));if(!a){for(var d in h)document.addEventListener(d,h[d],!0);a=!0}},t=function(){if(a){for(var b in h)document.removeEventListener(b,h[b],!0);a=!1}d=
[]},l=function(a){return-1<a.indexOf("*")||-1<a.indexOf(String.fromCharCode(8226))};return{setup:p,teardown:t,getUnmaskedValue:function(a){if(l(a.inputValue)){var b;for(b=0;b<d.length;++b){var c=d[b];if(c.input===a.input&&c.value!==a.inputValue)return c.value}if(a.form)for(b=0;b<a.form.length;++b){var e=c=a.form[b],f=a.inputValue;if(e.value&&!l(e.value)&&e.value.length===f.length&&(e.value[0]===f[0]||e.value[e.value.length-1]===f[f.length-1]))return c.value}}return a.inputValue},getUsername:function(){"undefined"===
typeof b.username&&b.usernames&&0<b.usernames.length&&(b.username=LPContentScriptTools.findText({searches:b.usernames}));return b.username}}}();Topics.get(Topics.INITIALIZED).subscribe(function(){bg.LPTabState.getState(function(b){b.enabled&&(u.setup(b),window===top&&bg.LPTabState.getSiteNotification({callback:x}))})});return{formExists:A,showSiteNotification:function(b){b.postSetup=function(){Topics.get(Topics.SITE_NOTIFICATION).publish(f)};var f=LPFrame.openDialog("contentScriptSite",b,{css:{top:10,
right:10}})}}}();
