Interfaces=function(){var k=function(e,d){this.type=e;if(this.options=d)this.options.include&&(this.options.include=[].concat(this.options.include)),this.options.exclude&&(this.options.exclude=[].concat(this.options.exclude))};k.prototype.requiredBy=function(e){var d;if(e&&this.options){if(this.options.include){for(d=0;d<this.options.include.length;++d)if(this.options.include[d]===e)return!0;return!1}if(this.options.exclude)for(d=0;d<this.options.exclude.length;++d)if(this.options.exclude[d]===e)return!1}return!0};
k.prototype.isSyncronized=function(){return this.options&&!0===this.options.sync};k.prototype.isSyncronousFunction=function(){return this.type===Interfaces.TYPE_SYNC_FUNCTION};k.prototype.isFunction=function(){return this.type===Interfaces.TYPE_FUNCTION||this.type===Interfaces.TYPE_SYNC_FUNCTION};k.prototype.isConstructor=function(){return this.type===Interfaces.TYPE_CONSTRUCTOR};k.prototype.isPrimitive=function(){return!this.isFunction()&&!this.isConstructor()};k.prototype.shouldSendIndirect=function(){return this.isPrimitive()?
this.options&&"undefined"!==typeof this.options.sendIndirect?this.options.sendIndirect:!0:this.options&&!0===this.options.sendIndirect};k.prototype.allowWrite=function(){return this.options&&!0===this.options.write};k.prototype.addIncludes=function(e){this.options=this.options||{};this.options.include=this.options.include.concat(e)};var v=function(){var e=function(a,b){return function(c){if(b.hasOwnProperty(c))return a[c];throw c+" is not defined in the interface.";}},d=function(a,b,c,d){var f=function(b,
d,f){if(!b.allowWrite())throw c.concat(d)+" is not writeable.";if(b&&typeof f===b.type)a[d]=f;else throw d+" is not defined in the interface.";};return d.direct?function(a,c){f(b[a],a,c)}:function(a,e){var g=b[a];f(g,a,e);g.shouldSendIndirect()&&d.requestFunction({cmd:"LPData.setValue",args:[c.concat(a),e]})}},q=function(a,b){return function(){return b.apply(a,arguments)}},g=function(a,b,c){if("function"===typeof c.requestFunction)return function(){for(var d=[],f=0,e=arguments.length;f<e;++f)d.push(arguments[f]);
return c.requestFunction({cmd:0<a.length?a.concat(b):b,args:d})};throw"requestFunction must be specified for this interface since it is not direct access.";},u=function(a,b,c){return function(){"function"===typeof b&&b.apply(a,arguments);"function"===typeof c&&c.apply(a,arguments)}},l=function(a,b,c,p,f,m){var t=!1,r=[],h;for(h in p){var n=p[h];n instanceof k?n.isFunction()?!n.requiredBy(m.context)||n.isSyncronousFunction()&&m.asyncOnly||(m.direct||n.isSyncronousFunction()?b&&"function"===typeof b[h]?
(a[h]=q(b,b[h]),!m.direct&&n.shouldSendIndirect()&&(a[h]=u(a,a[h],g(f,h,m)))):r.push(n.type+": "+f.concat(h).join(".")):a[h]=g(f,h,m)):n.isConstructor()?n.requiredBy(m.context)&&!m.asyncOnly&&(b&&"function"===typeof b[h]?a[h]=b[h]:r.push(n.type+": "+f.concat(h).join("."))):t=!0:(a.hasOwnProperty(h)||(a[h]={}),l(a[h],b?b[h]:b,c?c[h]:c,p[h],f.concat(h),m))}t&&(a.get=e(c,p),a.set=d(c,p,f,m));if(0<r.length)throw"Background instance does not support the following:\n"+r.join("\n");return a};return function(a,
b){return l(b.instance||{},b.source||b.sourceFunctions,b.source||b.sourceData,a,[],b)}}(),w=function(){var e={},d={},q=function(d,e,l,a){var b=[],c;for(c in d){var g=a?a.concat(c):[c],f=d[c];f instanceof k?f.isPrimitive()&&f.requiredBy(e)&&(!l||f.isSyncronized())&&b.push({sourceFunction:f.options&&f.options.sourceFunction,path:g}):b=b.concat(q(f,e,l,g))}return b};return function(g){var k={};if(g.context){var l;l=g.context;var a;l=[].concat(l);for(var b=0;b<l.length;++b){var c=l[b];g.syncronizedOnly?
(a=d[c],"undefined"===typeof a&&(a=d[c]=q(g["interface"],c,!0))):(a=e[c],"undefined"===typeof a&&(a=e[c]=q(g["interface"],c,!1)))}l=a;a=0;for(b=l.length;a<b;++a){var c=l[a],p;p=c.sourceFunction?"function"===typeof c.sourceFunction?c.sourceFunction():LPReflection.callFunction(null,c.sourceFunction,[],{context:g.source}):LPReflection.getValue(g["interface"],c.path,{context:g.source});LPReflection.setValue(null,c.path,p,{context:k})}}return k}}();return{TYPE_CONSTRUCTOR:"contsructor",TYPE_SYNC_FUNCTION:"synchronous function",
TYPE_FUNCTION:"function",TYPE_STRING:"string",TYPE_BOOLEAN:"boolean",TYPE_NUMBER:"number",TYPE_OBJECT:"object",Definition:k,extend:function(e,d){for(var k in d){var g=d[k];switch(typeof g){case "object":e.hasOwnProperty(k)?Interfaces.extend(e[k],g):e[k]=g;break;default:e[k]=g}}},createInstance:v,getPrimitives:w,getName:function(e){for(var d in this)if(e===this[d])return d;throw Error("Could not find interface name.");}}}();
