"function"!==typeof Object.create&&(Object.create=function(f){function k(){}k.prototype=f;return new k});
(function(){var f=function(f,g){this._data=f||{};if(this._sharedGroup=g){var e=this.getTopLevelGroupName();g.getName()!==e&&(this._data.group=g.getName()+this._data.group.substring(e.length))}else!this.useSharePrefix()&&this._data.group&&0===this._data.group.indexOf(this.SHARED_FOLDER_NAME_PREFIX)&&(this._data.group=this._data.group.substring(this.SHARED_FOLDER_NAME_PREFIX.length))};VaultItemBase=function(k,g){this._views=[];f.apply(this,arguments)};VaultItemBase.prototype.refresh=function(k,g){f.apply(this,
arguments);return this}})();VaultItemBase.prototype.defaultFields=function(f,k){k=k||this._data;for(var g in f)void 0===k[g]&&(k[g]=f[g])};VaultItemBase.prototype.SHARED_FOLDER_NAME_PREFIX="Shared-";VaultItemBase.prototype.useSharePrefix=function(){return this.getSharedGroup()?this._sharedGroup.useSharePrefix():!1};VaultItemBase.prototype.getTopLevelGroupName=function(){var f=this._data.group||"",k=f.indexOf("\\");return-1<k?f.substring(0,k):f};
VaultItem=function(){var f={pwprotect:!1};return function(k,g){VaultItemBase.call(this,k,g);this.defaultFields(f)}}();VaultItem.prototype=Object.create(VaultItemBase.prototype);VaultItem.prototype.constructor=VaultItem;
AccountBase=function(){var f={action:"",aid:"0",basic_auth:"0",captcha_id:"",custom_js:"",extra:"",fields:[],group:"",fiid:"",getpw:!1,individualshare:!1,last_touch:"0",method:"",newvalues:[],realm_data:"",sharedfromuid:"",submit_id:"",urid:"0",fav:"0",username:"",password:""};return function(k,g){VaultItem.call(this,k,g);this.defaultFields(f)}}();AccountBase.prototype=Object.create(VaultItem.prototype);AccountBase.prototype.constructor=AccountBase;
AccountBaseWithFields=function(f,k){AccountBase.call(this,f,k)};AccountBaseWithFields.prototype=Object.create(AccountBase.prototype);AccountBaseWithFields.prototype.constructor=AccountBaseWithFields;Account=function(f,k){AccountBaseWithFields.call(this,f,k);this._data.sn=0};Account.prototype=Object.create(AccountBaseWithFields.prototype);Account.prototype.constructor=Account;Account.prototype.getDisplayClass=function(){return AccountDisplay};Account.prototype.TYPE="Account";
Group=function(f,k){AccountBase.call(this,f,k);this._data.url="http://group"};Group.prototype=Object.create(AccountBase.prototype);Group.prototype.constructor=Group;Group.prototype.getDisplayClass=function(){return GroupDisplay};DummyGroup=function(f,k){Group.call(this,{group:f},k)};DummyGroup.prototype=Object.create(Group.prototype);DummyGroup.prototype.constructor=DummyGroup;DummyGroup.prototype.getDisplayClass=function(){return DummyGroupDisplay};DefaultGroup=function(f){DummyGroup.call(this,f)};
DefaultGroup.prototype=Object.create(DummyGroup.prototype);DefaultGroup.prototype.constructor=DefaultGroup;DefaultGroup.prototype.getDisplayClass=function(){return DefaultGroupDisplay};
(function(){var f={accepted:"1",association:"0",associative:"0",can_administer:"1",cgid:"0",deleted:"0",download:"1",give:"1",id:"0",invisible:"0",outside_enterprise:"0",readonly:"0",shareid:"0"},k=function(g,e){this.useSharePrefix()&&0!==this._data.group.indexOf(this.SHARED_FOLDER_NAME_PREFIX)&&(this._data.group=this.SHARED_FOLDER_NAME_PREFIX+this._data.group);this._data.group=this.getTopLevelGroupName();e=e||{};var a=LPTools.get_gmt_timestamp();f.create=a;f.last_modified=a;this.defaultFields(f,
e);this._shareInfo=e;this._shareInfo.name=this.getShareGroupName();this._shareInfo.decsharename=this._data.group;this.setID(this._data.aid)};SharedGroup=function(g,e){Group.call(this,g);k.apply(this,arguments)};SharedGroup.prototype=Object.create(Group.prototype);SharedGroup.prototype.constructor=SharedGroup;SharedGroup.prototype.refresh=function(g,e){Group.prototype.refresh.call(this,g);k.apply(this,arguments);return this}})();SharedGroup.prototype.getDisplayClass=function(){return SharedGroupDisplay};
LinkedGroup=function(f,k){SharedGroup.call(this,f,k)};LinkedGroup.prototype=Object.create(SharedGroup.prototype);LinkedGroup.prototype.constructor=LinkedGroup;LinkedGroup.prototype.getDisplayClass=function(){return LinkedGroupDisplay};EmergencyAccessGroup=function(f,k){LinkedGroup.call(this,f,k)};EmergencyAccessGroup.prototype=Object.create(LinkedGroup.prototype);EmergencyAccessGroup.prototype.constructor=EmergencyAccessGroup;EmergencyAccessGroup.prototype.getDisplayClass=function(){return EmergencyAccessGroupDisplay};
(function(){var f=function(f,g,e){this._data.sn=1;this._data.url="http://sn";this._attachments=e||[];f=0;for(g=this._attachments.length;f<g;++f)this._attachments[f].setParentNote(this)};Note=function(k,g,e){AccountBase.call(this,k,g);f.apply(this,arguments)};Note.prototype=Object.create(AccountBase.prototype);Note.prototype.constructor=Note;Note.prototype.refresh=function(k,g,e){AccountBase.prototype.refresh.apply(this,arguments);f.apply(this,arguments);return this}})();
Note.prototype.getDisplayClass=function(){return NoteDisplay};Note.prototype.TYPE="Note";
FormFill=function(){var f={address1:"",address2:"",address3:"",bankacctnum:"",bankname:"",bankroutingnum:"",birthday:"",cccsc:"",ccexp:"",ccissuenum:"",ccname:"",ccnum:"",ccstart:"",city:"",company:"",country:"",country_cc3l:"",country_name:"",county:"",creditmon:"",customfield1alttext:"",customfield1cfid:"0",customfield1text:"",customfield1value:"",customfield2alttext:"",customfield2cfid:"0",customfield2text:"",customfield2value:"",customfield3alttext:"",customfield3cfid:"0",customfield3text:"",
customfield3value:"",deleteext:0,driverlicensenum:"",email:"",eveext:"",evephone:"",evephone3lcc:"",fax:"",fax3lcc:"",faxext:"",ffid:0,firstname:"",firstname2:"",firstname3:"",gender:"",group:"",lastname:"",lastname2:"",lastname3:"",middlename:"",mobileemail:"",mobileext:"",mobilephone:"",mobilephone3lcc:"",notes:"",phone:"",phone3lcc:"",phoneext:"",profilelanguage:"",profilename:"",profiletype:0,ssn:"",state:"",state_name:"",taxid:"",timezone:"",title:"",username:"",zip:""};return function(k,g){VaultItem.call(this,
k,g);this.defaultFields(f);void 0===this._data.decprofilename&&(this._data.decprofilename=LPProxy.decryptMobile(this._data.profilename,!0,this.getKey()))}}();FormFill.prototype=Object.create(VaultItem.prototype);FormFill.prototype.constructor=FormFill;FormFill.prototype.getDisplayClass=function(){return FormFillDisplay};FormFill.prototype.TYPE="FormFill";Attachment=function(f){VaultItemBase.call(this,f);this._filename=null};Attachment.prototype=Object.create(VaultItemBase.prototype);
Attachment.prototype.constructor=Attachment;Attachment.prototype.getDisplayClass=function(){return AttachmentDisplay};Identity=function(f){VaultItemBase.call(this,f);this.defaultFields({iid:"0"});this._enabled=!1;void 0===this._data.deciname&&(this._data.deciname=LPProxy.decrypt(this._data.iname,this.getKey()))};Identity.prototype=Object.create(VaultItemBase.prototype);Identity.prototype.constructor=Identity;Identity.prototype.getDisplayClass=function(){return IdentityDisplay};
AllIdentity=function(){Identity.call(this);this._data.deciname="All";this._data.iid=""};AllIdentity.prototype=Object.create(Identity.prototype);AllIdentity.prototype.constructor=AllIdentity;AllIdentity.prototype.getDisplayClass=function(){return AllIdentityDisplay};Application=function(){var f={appaid:"0"};return function(k,g){AccountBaseWithFields.call(this,k,g);this.defaultFields(f);this.setSaveAll()}}();Application.prototype=Object.create(AccountBaseWithFields.prototype);
Application.prototype.constructor=AccountBaseWithFields;Application.prototype.getDisplayClass=function(){return ApplicationDisplay};Application.prototype.TYPE="Application";
(function(f,k,g,e){(function(){VaultItemBase.prototype.sortByFunction=function(b,a,c,h){b=b[c].apply(b);a=a[c].apply(a);return b>a?h?1:-1:b<a?h?-1:1:0};VaultItemBase.prototype.sortByTextFunction=function(){var b=function(b,a){var c=b[a].apply(b);return"string"===typeof c?c.toLowerCase():""};return function(a,c,h,l){a=b(a,h);c=b(c,h);return a>c?l?1:-1:a<c?l?-1:1:0}}();VaultItemBase.prototype.sortByNameAsc=function(b,a){return VaultItemBase.prototype.sortByTextFunction(b,a,"getName",!0)};VaultItemBase.prototype.sortByNameDesc=
function(b,a){return VaultItemBase.prototype.sortByTextFunction(b,a,"getName",!1)};VaultItemBase.prototype.lockForUpdate=function(){for(var b=0,a=this._views.length;b<a;++b)this._views[b].lockForUpdate()};VaultItemBase.prototype.unlock=function(){for(var b=0,a=this._views.length;b<a;++b)this._views[b].unlock()};VaultItemBase.prototype.updateViews=function(b,a){for(var c=this._views.slice(),d=0,l=c.length;d<l;++d)c[d].updateView(b,a)};VaultItemBase.prototype.destroyViews=function(){for(var b=this._views.slice(),
a=0,c=b.length;a<c;++a)b[a].destruct();this._views=[]};VaultItemBase.prototype.newDisplayObject=function(){return new (this.getDisplayClass())(this)};VaultItemBase.prototype.addView=function(b){this._views.push(b)};VaultItemBase.prototype.removeView=function(b){for(var a=0,c=this._views.length;a<c;++a)if(this._views[a]===b){this._views.splice(a,1);break}};VaultItemBase.prototype.isNew=function(){return"0"===this.getID()};VaultItemBase.prototype.createHandler=function(b){var a=this;if(1<arguments.length){for(var c=
[],h=1,l=arguments.length;h<l;++h)c.push(arguments[h]);return function(){b.apply(a,c)}}return function(){b.apply(a,arguments)}};VaultItemBase.prototype.update=function(b,a,c){e.removeItem(this);b&&(this._data=b);e.addItem(this);this._sharedGroup=a?a.getSharedGroup():null;g.getOption(c,"updateViews",!0)&&this.updateViews(a,c)};VaultItemBase.prototype.deleteUpdates=function(b){(void 0===b||b)&&this.publishSuccess(Strings.Vault.DELETED);this.destroyViews();e.removeItem(this)};VaultItemBase.prototype.getRepromptType=
function(){return null};VaultItemBase.prototype.publishAdd=function(b,a,c){e.addItem(this);this.publishSuccess(Strings.Vault.ADDED);Topics.get(b).publish(this,a,c)};VaultItemBase.prototype.getSuccessMessage=function(){return function(b,a){return 1<a?Strings.translateString("%1 items were %2.",a,b):Strings.translateString("%1 was %2.",this.toString(),b)}}();VaultItemBase.prototype.publishSuccess=function(b,a){Topics.get(Topics.SUCCESS).publish(this.getSuccessMessage(b,a))};VaultItemBase.prototype.handleClickEvent=
function(b,a){switch(b){case Constants.ACTION_EDIT:this.edit(a);break;case Constants.ACTION_DELETE:this.deleteItem(a);break;case Constants.ACTION_PURGE:this.purge(a);break;case Constants.ACTION_RESTORE:this.restore(a);break;case Constants.ACTION_MOVE_TO_FOLDER:this.moveToFolder(a.group,a.itemsForAction,a)}};VaultItemBase.prototype.isShared=function(){var b=this.getSharedGroup();return b&&!(b instanceof LinkedGroup)};VaultItemBase.prototype.shouldPasswordProtectShare=function(){return!0};VaultItemBase.prototype.passwordProtect=
function(b,a){for(var c=g.getOption(a,"itemsForAction",[this]),d=!1,l={},e=0,m=c.length;e<m;++e){var f=c[e];if(f.passwordProtected()){d=!0;break}f.shouldPasswordProtectShare()&&f.isShared()&&(l.switch_f_prompt=!0)}a=a||{};d?delete a.types:a.types=g.getProperties(l).concat(g.getOption(a,"types",[]));this.reprompt(b,a)};VaultItemBase.prototype.reprompt=function(b,a){return e.reprompt(this.createHandler(function(){b.apply(this)}),a)};var a=function(b,a){for(var c=b.itemsForAction,d,l=0,e=c.length;l<
e;++l){var m=c[l];if(void 0===d)d=m.getShareID();else if(d!==m.getShareID()){Topics.get(Topics.ERROR).publish(Strings.translateString("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return}}a(b,d)};VaultItemBase.prototype.purge=function(){var b=function(b){return 1<b.length?Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,this instanceof Group?Strings.Vault.FOLDER_PURGE:Strings.Vault.SELECTED_PURGE):Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,
b[0].toString())},d=function(a,d){var c=a.itemsForAction;LPRequest.makeUpdateRequest(e.purgeDeletedItems,{parameters:[c,d],success:function(){for(var b=0,a=c.length;b<a;b++)c[b].deleteUpdates(!1);c[0].publishSuccess(Strings.Vault.PURGED,c.length)},confirm:{title:Strings.Vault.PURGE,text:b.call(this,c)}})};return function(b){a(b,d)}}();VaultItemBase.prototype.restore=function(){var b=function(b){return 1<b.length?Strings.translateString(Strings.VaultDynamic.CONFIRM_RESTORE,this instanceof Group?Strings.Vault.FOLDER_PURGE:
Strings.Vault.SELECTED_PURGE):Strings.translateString(Strings.VaultDynamic.CONFIRM_RESTORE,b[0].toString())},d=function(a,d){var c=a.itemsForAction;LPRequest.makeRequest(e.restoreDeletedItems,{parameters:[c,d],success:function(){for(var b=0,a=c.length;b<a;b++)c[b].deleteUpdates(!1);c[0].publishSuccess(Strings.Vault.RESTORED,c.length);e.refreshSites()},confirm:{title:Strings.Vault.RESTORE,text:b.call(this,c)}})};return function(b){a(b,d)}}();VaultItemBase.prototype.confirmDelete=function(b){return b&&
1<b.length?{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete %1?",Strings.translateString("the selected items"))}:{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete %1?",this.toString())}};VaultItemBase.prototype.isDeleted=function(){return"1"===this._data.deleted};VaultItemBase.prototype.getName=function(){var b=this._data.name;return b?b:""};VaultItemBase.prototype.getURL=function(){return this._data.url};VaultItemBase.prototype.isFavorite=
function(){return"1"===this._data.fav};VaultItemBase.prototype.setFavorite=function(b){this._data.fav=b?"1":"0"};VaultItemBase.prototype.processEnteredData=function(b,a,c){for(var d in b)c=this._data[d],"boolean"!==typeof b[d]||"0"!==c&&"1"!==c||(b[d]=b[d]?"1":"0");a&&a.getSharedGroup()?b.sharefolderid=a.getShareID():delete b.sharefolderid};VaultItemBase.prototype.saveFromDialog=function(b,a,c){var d=a?a.getKey():this.getKey();this.processEnteredData(b,a,d,c);b=f.extend({},this._data,b);this.save(b,
a,c)};VaultItemBase.prototype.addFromDialog=function(b,a,c){var d=a?a.getKey():this.getKey();this.processEnteredData(b,a,d,c);f.extend(this._data,b);this.add(a,c)};VaultItemBase.prototype.getFormData=function(b){var a={},c;for(c in b){b="pwprotect"===c||"autologin"===c||"never_autofill"===c||"fav"===c;var h=this._data[c];b&&"1"===h?a[c]=!0:b&&"0"===h?a[c]=!1:void 0!==h&&"object"!==typeof h&&(a[c]=h)}return a};VaultItemBase.prototype.getKey=function(){var a=this.getSharedGroup();return a?a.getKey():
e.getLocalKey()};VaultItemBase.prototype.getShareID=function(){var a=this.getSharedGroup();return a?a.getID():this._data.sharefolderid||""};VaultItemBase.prototype.isReadOnly=function(){var a=this.getSharedGroup();return a?a.isReadOnly():!1};VaultItemBase.prototype.getShareInfo=function(){var a=this.getSharedGroup();return a?a._shareInfo:null};VaultItemBase.prototype.getSharedGroup=function(){return this._sharedGroup?this._sharedGroup:null};VaultItemBase.prototype.getURLArguments=function(a,d,c){return f.param(this.getPostData(a,
d,c))};VaultItemBase.prototype.getGroupName=function(){return this._data.group};VaultItemBase.prototype.getGroupParentName=function(){var a=this._data.group,d=a.lastIndexOf("\\");return 0<d?a.substring(0,d):""};VaultItemBase.prototype.getSearchTokens=function(a){return[this.getName()]};VaultItemBase.prototype.getPostData=function(a,d,c){a={extjs:1,localupdate:1,ajax:1};c&&(c.source&&(a.source=c.source),c.folder&&(a.folder=c.folder));return a};VaultItemBase.prototype.passwordProtected=function(){return this.getRepromptType()&&
bg.get("g_prompts")[this.getRepromptType()]};VaultItemBase.prototype.getLastTouch=function(){return 0};VaultItemBase.prototype.edit=function(a){Topics.get(this.getEditTopicID()).publish({vaultItem:this,dialogActions:a.dialogActions})};VaultItemBase.prototype.encryptIfNecessary=function(a,d,c){var b=this.getKey();return e.decryptMobile(this._data[a],!0,b)!==d||c!==b?e.encryptMobile(d,!0,c):this._data[a]}})();(function(){VaultItem.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_SHARE:this.share(b);
break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};VaultItem.prototype.share=function(a){this.passwordProtect(function(){Topics.get(Topics.ITEM_SHARE).publish(a.itemsForAction)},a)};VaultItem.prototype.deleteItem=function(a){for(var b=a&&a.itemsForAction||[this],d,c=0,h=b.length;c<h;++c){var l=b[c];if(l.isReadOnly()){Topics.get(Topics.ERROR).publish(Strings.translateString("You do not have permission to %1 %2",Strings.translateString("delete items from"),l.getSharedGroup().toString()));
return}if(void 0===d)d=l.getSharedGroup();else if(d!==l.getSharedGroup()){Topics.get(Topics.ERROR).publish(Strings.translateString("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return}}this.passwordProtect(function(){LPRequest.makeLockItemUpdateRequest(e.deleteItem,{parameters:[b],items:b,success:function(){b[0].publishSuccess(Strings.Vault.DELETED,b.length);for(var c=0,d=b.length;c<d;++c)b[c].deleteUpdates(!1);a.success&&
a.success()},confirm:g.getOption(a,"confirm",!0)?b[0].confirmDelete(b):null})},a)};(function(){VaultItem.prototype.moveToFolderPostCheck=function(c,h,l,n){if(0<c.length||0<h.length){var m=g.getOption(n,"saveFromDialog",!1),f=function(){var f=c.concat(h);LPRequest.makeLockItemUpdateRequest(e.moveToFolder,{parameters:[f,l],items:f,success:function(d){a(c,d,l,n);b(d,l,n);m||f[0].publishSuccess("moved to "+l.toString(),f.length);n&&n.success&&n.success()},confirm:d(c,l)})};m?f():this.passwordProtect(f,
{itemsForAction:c.concat(h)})}};Group.prototype.moveToFolderPostCheck=function(c,h,l,n){var m=f.extend(!0,{},this._data);m.group=l.getName()+"\\"+this.getGroupName();(function(h){LPRequest.makeUpdateRequest(e.renameGroup,{parameters:[h,m],success:function(d){a([h],d,l,n);a(c,d,l,f.extend(n,{updateViews:!1}));b(d,l,n);h.publishSuccess("moved to "+l.toString())},confirm:d(c,l)})})(this)};var a=function(a,b,d,e){for(var c=0,h=a.length;c<h;++c){var l=a[c],n=l.getID();b&&b[n]?(l.update(b[n],d,e),delete b[n]):
l.update(l._data,d,e)}},b=function(a,b,d){for(var c in a){var h=a[c];h.sn?(new Note(h,b.getSharedGroup())).publishAdd(Topics.NOTE_ADDED,b,d):h.appaid?(new Application(h,b.getSharedGroup())).publishAdd(Topics.SITE_ADDED,b,d):(new Account(h,b.getSharedGroup())).publishAdd(Topics.SITE_ADDED,b,d)}},d=function(a,b){for(var c=null,d=!1,h=!1,e=!1,f=b?b.getSharedGroup():null,g=0,k=a.length;g<k;++g){var p=a[g].getSharedGroup();p?f?p!==f&&(d=!0):p instanceof LinkedGroup||(e=!0):!f||f instanceof LinkedGroup||
(h=!0)}if(d||h||e)c=[],d&&c.push(Strings.translateString("You are moving items to a different shared folder. This may change who has access to them.")),h&&c.push(Strings.translateString("You are moving sites to a shared folder. Others may now have access to them.")),e&&c.push(Strings.translateString("You are moving items from a shared folder into your vault. Others may lose access to them.")),c.push(Strings.translateString("Do you want to continue?")),c={title:Strings.translateString("Shared Folders"),
text:c};return c};AccountBase.prototype.saveFromDialog=function(a,b){var c=d([this],b);if(c){for(var h=[VaultItem.prototype.saveFromDialog],e=0,f=arguments.length;e<f;++e)h.push(arguments[e]);c.handler=this.createHandler.apply(this,h);Topics.get(Topics.CONFIRM).publish(c)}else VaultItem.prototype.saveFromDialog.apply(this,arguments)};VaultItem.prototype.moveToFolder=function(a,b,d){if(a.isReadOnly())Topics.get(Topics.ERROR).publish(Strings.translateString("You do not have permission to %1 %2",Strings.translateString("move items to"),
a.toString()));else{for(var c=[],h=[],e=[],l=[],f=a.getSharedGroup(),k=0,p=b.length;k<p;++k){var r=b[k];r.isReadOnly()?e.push(r):f&&r._data.individualshare?0<parseInt(r._data.sharedfromaid)?h.push(r):c.push(r):l.push(r)}b=[];0<h.length&&b.push({type:"alert",title:Strings.translateString("Error"),text:[Strings.translateString("The following items have been individually shared with you and cannot be moved into a shared folder:"),g.buildDialogItemContainer(h)]});0<e.length&&b.push({type:"alert",title:Strings.translateString("Error"),
text:[Strings.translateString("You do not have permission to move the following items from their respective shared folders:"),g.buildDialogItemContainer(e)]});0<c.length&&b.push({type:"confirmation",title:Strings.translateString("Error"),text:[Strings.translateString("The following items have already been shared individually and cannot be moved to a shared folder:"),Strings.translateString("Would you like to make a copy?"),g.buildDialogItemContainer(c)],closeHandler:function(){c.splice(0,c.length)}});
0<b.length?g.openAlerts(b,function(b){return function(){b.moveToFolderPostCheck.call(b,l,c,a,d)}}(this)):this.moveToFolderPostCheck.call(this,l,c,a,d)}}})();VaultItem.prototype.passwordProtected=function(){return this._data.pwprotect||VaultItemBase.prototype.passwordProtected.apply(this,arguments)};VaultItem.prototype.getPostData=function(a,b){var d=VaultItemBase.prototype.getPostData.apply(this,arguments);a.pwprotect&&(d.pwprotect="on");return d}})();(function(){AccountBase.prototype.getLastTouch=
function(){return parseInt(this._data.last_touch)};AccountBase.prototype.getID=function(){return this._data.aid};AccountBase.prototype.setID=function(a){this._data.aid=a};AccountBase.prototype.getFormData=function(a){var b=VaultItem.prototype.getFormData.apply(this,arguments);b.extra=e.decryptMobile(this._data.extra,!0,this.getKey());return b};AccountBase.prototype.getPostData=function(a,b){var d=VaultItem.prototype.getPostData.apply(this,arguments),c=b?b.getKey():e.getLocalKey();d.aid=this.getID();
d.name=e.encryptWithKey(a.name,c);d.extra=e.encryptWithBTOA(a.extra);var h=b.getSharedGroup();h?(d.sharedfolderid=h.getID(),d.grouping=e.encryptWithKey(a.group.substring(h.getName().length+1),c)):d.grouping=e.encryptWithKey(a.group,c);a.pwprotect&&(d.pwprotect="on");"1"===a.fav&&(d.fav="on");return d};AccountBase.prototype.checkForSharedGroupChange=function(a){var b=this.getSharedGroup();a=a.getSharedGroup();return(null!==b||null!==a)&&b!==a};AccountBase.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_COPY_USERNAME:this.copyUsername();
break;case Constants.ACTION_COPY_PASSWORD:this.copyPassword(b);break;case Constants.ACTION_CLONE:this.cloneItem();break;default:VaultItem.prototype.handleClickEvent.apply(this,arguments)}};AccountBase.prototype.getSearchTokens=function(a){var b=VaultItem.prototype.getSearchTokens.apply(this,arguments);a.searchNotes&&this._data.extra&&!this.passwordProtected()&&b.push(e.decryptMobile(this._data.extra,!0,this.getKey()));return b};AccountBase.prototype.getCloneData=function(){var a=this.getFormData(DialogInput.getProperties(this._data));
a.name=a.name+" - "+Strings.translateString("Copy");delete a.aid;return a};AccountBase.prototype.processEnteredData=function(a,b,d){VaultItem.prototype.processEnteredData.apply(this,arguments);a.encgroup=this.encryptIfNecessary("encgroup",a.group,d);a.encname=this.encryptIfNecessary("encname",a.name,d);a.action&&(a.action=bg.AES.bin2hex(a.action))};AccountBase.prototype.isShared=function(){return VaultItem.prototype.isShared.apply(this,arguments)||this._data.individualshare||this._data.sharedfromaid};
AccountBase.prototype.isSharingEnabled=function(){return null===this.getSharedGroup()&&(!this._data.individualshare||!this._data.sharedfromaid||""===this._data.sharedfromaid)};AccountBase.prototype.copyUsername=function(){e.copyUsername(this)};AccountBase.prototype.copyPassword=function(a){this.passwordProtect(function(){e.copyPassword(this,a)})};AccountBase.prototype.isReceivedShare=function(){return this._data.individualshare&&this._data.sharedfromaid}})();(function(){AccountBaseWithFields.prototype.REPROMPT_TYPE_VIEW_PW=
"view_pw_prompt";AccountBaseWithFields.prototype.getFormData=function(a){var b=AccountBase.prototype.getFormData.apply(this,arguments);b.fields=[];for(var d=0,c=this._data.fields.length;d<c;++d){var h=this._data.fields[d],e={name:h.name||h.id,type:h.type,value:this.getFieldValue(h,!0),formname:h.formname};"checkbox"===e.type&&(e.valueAttribute=h.value);b.fields.push(e)}b.save_all=this._data.save_all;return b};AccountBaseWithFields.prototype.processEnteredData=function(a,b,d,c){AccountBase.prototype.processEnteredData.apply(this,
arguments);var h=this.getKey(),e=a.unencryptedUsername;a.username=this.encryptIfNecessary("username",a.unencryptedUsername,d);a.password=this.encryptIfNecessary("password",a.password,d);a.extra=this.encryptIfNecessary("extra",a.extra,d);if(a.fields)for(var n=0;n<a.fields.length;++n){var m=a.fields[n],f=this.getFieldValue(m),g=this._data.fields[n];f!==this.getFieldValue(g,!0)||h!==d||m.formname!==g.formname||m.name!==g.name?(this.processEnteredFieldData(m,b,d),f===e&&"password"!==m.type?m.value=a.username:
a.password&&"password"===m.type?m.value=a.password:c.saveFields=!0):a.fields[n]=g}};AccountBaseWithFields.prototype.getFieldValue=function(a,b){var d=null;if(a)switch(d=a.value,a.type){case "checkbox":void 0!==a.checked&&(d=a.checked);break;case "radio":case "select":case "select-one":break;default:b&&(d=e.decryptMobile(a.value,!0,this.getKey()))}return d};AccountBaseWithFields.prototype.processEnteredFieldData=function(a,b,d){this.defaultFieldValues(a);switch(a.type){case "checkbox":a.checked=a.value;
a.value=a.valueAttribute||"";break;case "radio":case "select":case "select-one":break;default:void 0===d&&(d=b?b.getKey():this.getKey()),a.value=e.encryptMobile(a.value,!0,d)}};AccountBaseWithFields.prototype.getFieldPostData=function(a,b){var d=a.value;switch(a.type){case "checkbox":b&&(d+=a.checked?"-1":"-0");break;case "radio":d+="-1";break;case "select":case "select-one":break;default:d=e.encryptWithBTOA(a.value)}d={name:a.name,type:a.type,value:d,urid:a.urid};a.formname&&(d.formname=a.formname);
return d};AccountBaseWithFields.prototype.defaultFieldValues=function(){var a={checked:!1,formname:"",name:"",otherfield:!1,otherlogin:"0",type:"",urid:"0",url:"",value:""};return function(b){this.defaultFields(a,b)}}();AccountBaseWithFields.prototype.removeField=function(a){this._data.fields.splice(a,1)};AccountBaseWithFields.prototype.addField=function(a,b){void 0===b&&(b=this._data.fields);a=f.extend({},a);this.defaultFieldValues(a);b.push(a);return b.length-1};AccountBaseWithFields.prototype.canViewPassword=
function(){var a=this.getSharedGroup();return!a||a.hasPasswordAccess()};AccountBaseWithFields.prototype.cloneItem=function(){this.canViewPassword()?this.passwordProtect(function(){Topics.get(this.getEditTopicID()).publish({defaultData:this.getCloneData()})},{types:this.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to copy the password."))}})();(function(){Account.prototype.REPROMPT_TYPE="edit_site_prompt";Account.prototype.isURLLaunchable=
function(){return this._data.url&&0===this._data.url.indexOf("http://")||0===this._data.url.indexOf("https://")||0===this._data.url.indexOf("ssh://")};Account.prototype.isSharingEnabled=function(){return(!this._data.url||this.isURLLaunchable())&&AccountBase.prototype.isSharingEnabled.apply(this,arguments)};Account.prototype.isLaunchEnabled=function(){return this.isURLLaunchable()};Account.prototype.canViewPassword=function(){return AccountBaseWithFields.prototype.canViewPassword.apply(this,arguments)&&
!this.isReceivedShare()};Account.prototype.getEditTopicID=function(){return Topics.EDIT_SITE};Account.prototype.getPassword=function(){if(this._data.save_all){for(var a=0,b=this._data.fields.length;a<b;++a){var d=this._data.fields[a];if("password"===d.type&&d.value)return e.decryptMobile(d.value,!0,this.getKey())}return""}return e.decryptMobile(this._data.password,!0,this.getKey())};Account.prototype.getSearchTokens=function(a){var b=AccountBaseWithFields.prototype.getSearchTokens.apply(this,arguments),
d=this.getUsername();d&&b.push(d);this._data.url&&b.push(bg.hostof(this._data.url));return b};Account.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Account.prototype.getUsername=function(){if(this._data.save_all)for(var a=0,b=this._data.fields.length;a<b;++a){var d=this._data.fields[a];switch(d.type){case "text":case "email":case "tel":if(d.value)return e.decryptMobile(d.value,!0,this.getKey())}}void 0===this._data.unencryptedUsername&&(this._data.unencryptedUsername=e.decryptMobile(this._data.username,
!0,this.getKey()));return this._data.unencryptedUsername};Account.prototype.hasGeneratedPassword=function(){return this._data.genpw||0===this.getName().indexOf(Strings.Vault.GENERATED_PREFIX)};Account.prototype.toString=function(){return Strings.Vault.SITE+": "+this._data.name};Account.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_COPY_URL:this.copyURL();break;case Constants.ACTION_LAUNCH:this.launch();break;case Constants.ACTION_GO_TO_URL:this.goToURL();break;case Constants.ACTION_FILL_SITE:this.fill();
break;default:AccountBase.prototype.handleClickEvent.apply(this,arguments)}};Account.prototype.launch=function(){var a=function(){e.launchSite(this)};return function(){this.passwordProtect(a,{types:"login_site_prompt"})}}();Account.prototype.fill=function(){var a=function(){e.fillSite(this)};return function(){this.passwordProtect(a)}}();Account.prototype.copyPassword=function(a){this.canViewPassword()?this.passwordProtect(function(){e.copyPassword(this,a)},{types:this.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to copy the password."))};
Account.prototype.copyURL=function(){e.copyURL(this)};Account.prototype.goToURL=function(){e.goToURL(this)};Account.prototype.processEnteredData=function(a,b,d){a.save_all&&(delete a.unencryptedUsername,delete a.password);AccountBaseWithFields.prototype.processEnteredData.apply(this,arguments);a.url&&(a.url=bg.punycode.URLToASCII(a.url.trim()));a.realm_data&&(a.realm_data=e.encryptMobile(a.realm_data,!0,d))};Account.prototype.getFormData=function(a){var b=AccountBaseWithFields.prototype.getFormData.apply(this,
arguments);a.password&&(b.password=this.getPassword());a.unencryptedUsername&&(b.unencryptedUsername=this.getUsername());return b};Account.prototype.save=function(a,b,d){(function(c){LPRequest.makeUpdateRequest(e.saveSite,{parameters:[c,a,b,d],success:function(a){var h=c.getPassword();c.update(a,b);c.publishSuccess(Strings.Vault.SAVED);a=c.getPassword();if(h!==a){a=e.getDomain(c.getURL());for(var n=[],m=e.getSiteModels(),f=0,g=m.length;f<g;++f){var k=m[f];k!==c&&e.getDomain(k.getURL())===a&&k.getPassword()===
h&&n.push(k)}0<n.length&&dialogs.changePassword.open({domain:a,items:n,newPassword:c.getPassword()})}d.success&&d.success(c)}})})(this)};Account.prototype.add=function(a,b){(function(d){LPRequest.makeUpdateRequest(e.addSite,{parameters:[d,a,b],success:function(c){d.update(c,a);d.publishAdd(Topics.SITE_ADDED,a);b.success&&b.success(d)}})})(this)};Account.prototype.getPostData=function(a,b,d){var c=AccountBaseWithFields.prototype.getPostData.apply(this,arguments);c.username=a.username?e.encryptWithBTOA(a.username):
"";c.password=a.password?e.encryptWithBTOA(a.password):"";var h=bg.AES.url2hex(a.url);g.getOption(d,"saveFromSubmit",!1)?(c.ref=h,this.isNew()||(c.replacing=1)):c.url=h;a.never_autofill&&(c.never_autofill="on");a.autologin&&(c.autologin="on");if(a.save_all||g.getOption(d,"saveFromSubmit",!1))c.data=this.getFieldFormData(a.fields);a.save_all&&(c.save_all=1);c.urid=a.urid;"1"===a.basic_auth&&(c.basic_auth="1");a.realm_data&&(c.realm=e.encryptWithBTOA(a.realm_data));return c}})();Account.prototype.getFieldFormData=
function(a){for(var b="",d=0,c=a.length;d<c;++d)var h=a[d],e=this.getFieldPostData(h,!0).value,b=b+(h.formname+"\t"+encodeURIComponent(h.name)+"\t"+encodeURIComponent(e)+"\t"+encodeURIComponent(h.type)+"\n");return bg.AES.bin2hex(b)};(function(){Application.prototype.toString=function(){return Strings.Vault.APPLICATION+" "+this.getName()};Application.prototype.getEditTopicID=function(){return Topics.EDIT_APPLICATION};Application.prototype.shouldPasswordProtectShare=function(){return!1};Application.prototype.getCloneData=
function(){var a=AccountBaseWithFields.prototype.getCloneData.apply(this,arguments);delete a.appaid;return a};Application.prototype.getID=function(a){var b=this._data.appaid;a&&(b="app"+b);return b};Application.prototype.setID=function(a){this._data.appaid=a};Application.prototype.isSharingEnabled=function(){return!1};Application.prototype.getLastTouch=AccountBase.prototype.getLastTouch;Application.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_LAUNCH:e.launchApplication(this);
break;default:AccountBaseWithFields.prototype.handleClickEvent.apply(this,arguments)}};Application.prototype.update=function(){AccountBaseWithFields.prototype.update.apply(this,arguments);this.setSaveAll()};Application.prototype.addField=function(){AccountBaseWithFields.prototype.addField.apply(this,arguments);this.setSaveAll()};Application.prototype.removeField=function(){AccountBaseWithFields.prototype.removeField.apply(this,arguments);this.setSaveAll()};Application.prototype.setSaveAll=function(){for(var a,
b,d=0;d<this._data.fields.length;++d){var c=this._data.fields[d];switch(c.type){case "password":a=void 0===a?c:null;break;case "":b=void 0===b?c:null}}b&&a?(this._data.save_all=!1,this._data.unencryptedUsername=e.decryptMobile(b.value,!0,this.getKey()),this._data.username=b.value,this._data.password=a.value):(this._data.save_all=!0,delete this._data.unencryptedUsername,delete this._data.username,delete this._data.password)};Application.prototype.getUsername=function(){for(var a=0;a<this._data.fields.length;++a){var b=
this._data.fields[a];if("password"!==b.type&&b.value)return e.decryptMobile(b.value,!0,this.getKey())}};Application.prototype.getPassword=function(){for(var a=0;a<this._data.fields.length;++a){var b=this._data.fields[a];if("password"===b.type&&b.value)return e.decryptMobile(b.value,!0,this.getKey())}};Application.prototype.getFormData=function(a){var b=AccountBaseWithFields.prototype.getFormData.apply(this,arguments);this._data.save_all||(b.password=e.decryptMobile(this._data.password,!0,this.getKey()));
return b};Application.prototype.getSearchTokens=function(){var a=VaultItem.prototype.getSearchTokens.apply(this,arguments);a.push(this._data.appname);return a};Application.prototype.add=function(a,b){(function(d){LPRequest.makeUpdateRequest(e.addApplication,{parameters:[d,a,b],success:function(b){d.update(b,a);d.publishAdd(Topics.APPLICATION_ADDED,a)}})})(this)};Application.prototype.save=function(a,b,d){(function(c){LPRequest.makeUpdateRequest(e.saveApplication,{parameters:[c,a,b,d],success:function(){c.update(a,
b);c.publishSuccess(Strings.Vault.SAVED)}})})(this)};Application.prototype.getPostData=function(a,b){var d=AccountBase.prototype.getPostData.apply(this,arguments);d.appname=a.appname;if(a.fields)for(var c=0;c<a.fields.length;++c){var h=a.fields[c];d["fieldid"+c]=h.name||h.id;d["fieldtype"+c]=h.type;d["fieldvalue"+c]=this.getFieldPostData(h).value}d.appaid=d.aid;delete d.aid;this.isNew()||(d.cmd="updatelpaa");return d}})();(function(){Group.prototype.getDisplayClass=function(){return GroupDisplay};
Group.prototype.toString=function(){return Strings.Vault.GROUP+" "+this._data.group};Group.prototype.getName=function(){return this._data.group};Group.prototype.getGroupName=function(){return this._data.group.substring(this._data.group.lastIndexOf("\\")+1)};Group.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_RENAME:Topics.get(Topics.RENAME_FOLDER).publish(this);break;case Constants.ACTION_CREATE_SUB_FOLDER:Topics.get(Topics.CREATE_SUB_FOLDER).publish(this);break;case Constants.ACTION_SHARE:Topics.get(Topics.CREATE_SHARED_FOLDER).publish(this,
b.itemsForAction);break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};Group.prototype.confirmDelete=function(){return 0<this._itemCount?function(a){return function(b,d){Topics.get(Topics.CONFIRM).publish(Strings.Vault.DELETE,Strings.translateString("Are you sure you want to delete %1?",Strings.translateString("%1 containing %2 item(s)",a.toString(),a._itemCount)),b,d)}}(this):VaultItemBase.prototype.confirmDelete.apply(this)};Group.prototype.deleteItem=function(a){LPRequest.makeLockItemUpdateRequest(e.deleteFolder,
{parameters:[a.itemsForAction],items:a.itemsForAction,success:function(a){return function(){a.deleteUpdates()}}(this),confirm:this.confirmDelete()})};Group.prototype.add=function(a){(function(b){LPRequest.makeUpdateRequest(e.addGroup,{parameters:b,success:function(d){b.update(d,a);b.publishAdd(Topics.GROUP_ADDED,a)}})})(this)};Group.prototype.save=function(a,b){(function(d){LPRequest.makeUpdateRequest(e.renameGroup,{parameters:[d,a],success:function(){d.update(a,b);d.publishSuccess(Strings.Vault.RENAMED)}})})(this)};
Group.prototype.getFormData=function(a){var b=VaultItemBase.prototype.getFormData.apply(this,arguments);b.groupName=this.getGroupName();b.groupParent=this.getGroupParentName();return b};Group.prototype.processEnteredData=function(a){VaultItemBase.prototype.processEnteredData.apply(this,arguments);a.groupName&&(a.groupParent?(a.group=a.groupParent+"\\"+a.groupName,delete a.groupParent):a.group=a.groupName,delete a.groupName)}})();(function(){SharedGroup.prototype.setID=function(a){Group.prototype.setID.apply(this,
arguments);this._data.sharefolderid=a;this._shareInfo.id=a;this._shareInfo.shareid=a};SharedGroup.prototype.useSharePrefix=function(){return!0};SharedGroup.prototype.update=function(a){a&&(this._shareInfo.decsharename=a.group);Group.prototype.update.apply(this,arguments)};SharedGroup.prototype.isReadOnly=function(){return"1"===this._shareInfo.readonly};SharedGroup.prototype.canAdminister=function(){return"1"===this._shareInfo.can_administer};SharedGroup.prototype.isPending=function(){return"0"===
this._shareInfo.accepted};SharedGroup.prototype.canConvertToEnterprise=function(){return e.isEnterpriseUser()&&this.canAdminister()&&"1"===this._shareInfo.outside_enterprise&&"0"===this._shareInfo.cid};SharedGroup.prototype.isDownloaded=function(){return"1"===this._shareInfo.download};SharedGroup.prototype.hasPasswordAccess=function(){return"1"===this._shareInfo.give};SharedGroup.prototype.isDeleted=function(){return"1"===this._shareInfo.deleted};SharedGroup.prototype.isSharingEnabled=function(){return!1};
SharedGroup.prototype.getShareName=function(){return this._shareInfo.sharename};SharedGroup.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_START_DOWNLOADING:this.startDownloading();break;case Constants.ACTION_STOP_DOWNLOADING:this.stopDownloading();break;case Constants.ACTION_MANAGE:this.manage();break;case Constants.ACTION_RESTORE_SHARED_FOLDER:this.restoreSharedFolder();break;case Constants.ACTION_PURGE_SHARED_FOLDER:this.purgeSharedFolder();break;case Constants.ACTION_ACCEPT:this.accept();
break;case Constants.ACTION_REJECT:this.reject();break;default:Group.prototype.handleClickEvent.apply(this,arguments)}};SharedGroup.prototype.manage=function(){var a=function(){this.canConvertToEnterprise()?this.convertToEnterprise():Topics.get(Topics.EDIT_SHARED_FOLDER).publish(this)};return function(){this.passwordProtect(a)}}();SharedGroup.prototype.accept=function(){var a=function(a){Topics.get(Topics.UPDATE_NOTIFICATION_COUNT).publish();this.refresh(a.sharedFolder,a.shareInfo);this.update()};
return function(){LPRequest.makeRequest(bg.BackgroundServer.sharing.folder.accept,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},lockItems:!0,items:this,success:this.createHandler(a)})}}();SharedGroup.prototype.reject=function(){var a=function(){Topics.get(Topics.UPDATE_NOTIFICATION_COUNT).publish();this.deleteUpdates(!1)};return function(){LPRequest.makeUpdateRequest(bg.BackgroundServer.sharing.folder.reject,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},lockItems:!0,items:this,
success:this.createHandler(a),confirm:{title:Strings.Vault.REJECT,text:[Strings.translateString("Are you sure you want to reject %1?",this.toString())]}})}}();SharedGroup.prototype.stopDownloading=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(){LPRequest.makeUpdateRequest(e.stopDownloadingFolder,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},lockItems:!0,items:this,success:this.createHandler(a),successMessage:Strings.translateString("%1 will no longer be downloaded.",
this.toString()),confirm:{title:Strings.Vault.STOP_DOWNLOADING,text:[Strings.translateString("You are choosing to prevent downloading the contents of this Shared Folder to your vault. This is may improve performance if you have a lot of items in Shared Folders that are not regularly used. You may always begin to download the folder contents again in the Sharing Center."),Strings.translateString("Do you want to continue?")]}})}}();SharedGroup.prototype.add=function(){var a=function(a,d,c){var b=[],
e={};if(a){var n=a.getName(),f=c.getName();c=function(a){b.push(a.getID());e[a.getID()]=a._data.group.replace(n,f)};if(d)for(var g=0,k=d.length;g<k;++g){var q=d[g];q instanceof DummyGroup||c(q)}a instanceof DummyGroup||c(a)}return{itemsToMove:b,parentMap:e}};return function(b,d){var c=a(b,d,this);LPRequest.makeUpdateRequest(e.createSharedFolder,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},successMessage:0<c.itemsToMove.length?"":void 0,success:this.createHandler(function(a){this.refresh(a.sharedFolder,
a.shareInfo);this.update();0<c.itemsToMove.length?LPRequest.makeRequest(e.moveIntoSharedFolder,{params:f.extend(c,{toShareInfo:this._shareInfo}),success:this.createHandler(function(){this.publishAdd(Topics.GROUP_ADDED);d&&d.forEach(function(a){a.update(a._data,this)},this);b&&b.destruct()})}):(this.publishAdd(Topics.GROUP_ADDED),b&&b.destruct())})})}}();SharedGroup.prototype.deleteItem=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(){LPRequest.makeLockItemUpdateRequest(e.deleteSharedFolder,
{params:{sharedFolder:this._data,shareInfo:this._shareInfo},items:this,success:this.createHandler(a),successMessage:this.getSuccessMessage(Strings.Vault.DELETED),confirm:this.confirmDelete()})}}();SharedGroup.prototype.getFormData=function(a){var b=Group.prototype.getFormData.apply(this,arguments);b.groupName=this.getShareGroupName();return b};SharedGroup.prototype.processEnteredData=function(a){a.group=this.SHARED_FOLDER_NAME_PREFIX+a.groupName;delete a.groupName};SharedGroup.prototype.getShareGroupName=
function(a){void 0===a&&(a=this._data.group);return a.substring(this.SHARED_FOLDER_NAME_PREFIX.length)};SharedGroup.prototype.saveFromDialog=function(a,b){VaultItem.prototype.saveFromDialog.apply(this,arguments)};SharedGroup.prototype.save=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(b){LPRequest.makeUpdateRequest(e.renameSharedGroup,{params:{sharedFolder:b,shareInfo:this._shareInfo},success:this.createHandler(a),successMessage:this.getSuccessMessage(Strings.Vault.RENAMED)})}}();
SharedGroup.prototype.getKey=function(){return this._shareInfo.key};SharedGroup.prototype.getSharedGroup=function(){return this};SharedGroup.prototype.startDownloading=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(){LPRequest.makeRequest(e.startDownloadingFolder,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},lockItems:!0,items:this,success:this.createHandler(a),successMessage:Strings.translateString("%1 will now be downloaded.",this.toString())})}}();
SharedGroup.prototype.restoreSharedFolder=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(){LPRequest.makeRequest(e.restoreDeletedSharedFolder,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},lockItems:!0,items:this,success:this.createHandler(a),successMessage:this.getSuccessMessage(Strings.Vault.RESTORED)})}}();SharedGroup.prototype.purgeSharedFolder=function(){var a=function(){this.publishSuccess(Strings.Vault.PURGED);this.deleteUpdates(!1)};
return function(){LPRequest.makeLockItemUpdateRequest(e.purgeDeletedSharedFolder,{params:{sharedFolder:this._data,shareInfo:this._shareInfo},items:this,success:this.createHandler(a),confirm:{title:Strings.Vault.PURGE,text:Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,this.toString())}})}}();SharedGroup.prototype.convertToEnterprise=function(){var a=function(a){this.refresh(a.sharedFolder,a.shareInfo);this.update()};return function(){LPRequest.makeLockItemUpdateRequest(bg.BackgroundServer.sharing.folder.convertToEnterprise,
{params:{sharedFolder:this._data,shareInfo:this._shareInfo},items:this,success:this.createHandler(a),confirm:{title:Strings.translateString("Convert to Enterprise"),text:[Strings.translateString("This was a shared family folder, but you are now a part of a LastPass Enterprise account.  In order to continue administering this shared folder, you must move it into the enterprise account.  This may mean certain other members of the enterprise account will have access to it."),Strings.translateString("Do you want to continue?")]}})}}();
SharedGroup.prototype.toString=function(){return Strings.Vault.SHARED_FOLDER+": "+this.getName()}})();(function(){LinkedGroup.prototype.useSharePrefix=function(){return!1};LinkedGroup.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_UNLINK:this.unlink();break;default:SharedGroup.prototype.handleClickEvent.apply(this,arguments)}};LinkedGroup.prototype.unlink=function(){var a=function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Account (%1) unlinked.",this.getName()));
this.deleteUpdates(!1);e.refreshSites();Topics.get(Topics.ACCOUNT_UNLINKED).publish();for(var a=e.getFormFillModels(),d=0,c=a.length;d<c;++d){var h=a[d];h.getSharedGroup()===this&&h.deleteUpdates(!1)}};return function(){LPRequest.makeUpdateRequest(e.unlinkAccount,{params:{id:this.getID()},success:this.createHandler(a),confirm:{title:Strings.Vault.UNLINK,text:Strings.translateString("Are you sure you want to unlink your personal account (%1)",this.getName())}})}}();EmergencyAccessGroup.prototype.unlink=
function(){var a=function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Account (%1) unlinked.",this.getName()));this.deleteUpdates(!1)};return function(){LPRequest.makeUpdateRequest(e.unlinkEmergencyAccessAccount,{params:{folderID:this.getID(),email:this.getName()},success:this.createHandler(a),confirm:{title:Strings.Vault.UNLINK,text:Strings.translateString("Are you sure you want to unlink your personal account (%1)",this.getName())}})}}()})();(function(){Note.prototype.NOTE_TYPES=
{BANK:"Bank Account",CREDIT:"Credit Card",DATABASE:"Database",DRIVERS_LICENSE:"Driver's License",EMAIL:"Email Account",GENERIC:"Generic",HEALTH_INSURANCE:"Health Insurance",IM:"Instant Messenger",INSURANCE:"Insurance",MEMBERSHIP:"Membership",PASSPORT:"Passport",SERVER:"Server",SSN:"Social Security",SOFTWARE_LICENSE:"Software License",SSH_KEY:"SSH Key",WIFI:"Wi-Fi Password"};var a=function(){var a={},b;for(b in Note.prototype.NOTE_TYPES)a[Note.prototype.NOTE_TYPES[b]]=!0;return a}();Note.prototype.REPROMPT_TYPE=
"edit_sn_prompt";var b=function(a){return a?(a=a.match(/^Custom_(\d+)$/))&&2==a.length:!1},d=function(c){return b(c)||a[c]};Note.prototype.getNoteType=function(){if(void 0===this._noteType){var a=this._data.notetype?this._data.notetype:this.getKeyValuePairs().NoteType;this._noteType=d(a)?a:this.NOTE_TYPES.GENERIC}return this._noteType};Note.prototype.getTemplate=function(){return this._data.template};Note.prototype.isCustom=function(){return b(this.getNoteType())};Note.prototype.getAttachmentKey=
function(){return this._data.attachkey?bg.AES.hex2bin(e.decrypt(this._data.attachkey,this.getKey())):null};Note.prototype.cloneItem=function(){this.passwordProtect(function(){Topics.get(Topics.EDIT_NOTE).publish({defaultData:this.getCloneData()})})};Note.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Note.prototype.getEditTopicID=function(){return Topics.EDIT_NOTE};Note.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_COPY_NOTE:this.copyNote();break;case Constants.ACTION_COPY_KEY:this.copyPrivateKey();
break;default:AccountBase.prototype.handleClickEvent.apply(this,arguments)}};Note.prototype.copyNote=function(){var a=function(){e.copyToClipboard(this.getNoteField("Notes"));bg.loglogin(this.getID())};return function(){this.passwordProtect(a)}}();Note.prototype.copyPrivateKey=function(){var a=function(){var a=this.getPrivateKey();if(-1===a.indexOf("-----BEGIN")&&-1===a.indexOf("END-----"))e.copyToClipboard(a);else{for(var b=a.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/),a=a.split(/-----/),
b=b[1],c="",d=0,f=b.length;d<f;++d)c=":"!==b.charAt(d-1)?c+b[d].replace(/\u0020/g,"\n"):c+b[d];e.copyToClipboard("-----"+a[1]+"-----\n"+c+"\n-----"+a[3]+"-----")}bg.loglogin(this.getID())};return function(){this.passwordProtect(a)}}();Note.prototype.getNoteField=function(a){var b=this.getKeyValuePairs(),c;for(c in b){var d=b[c];if(c===a&&""!==d)return d}return null};Note.prototype.getPassword=function(){return this.getNoteField("Password")};Note.prototype.hasPassword=function(){return null!==this.getPassword()};
Note.prototype.getUsername=function(){return this.getNoteField("Username")};Note.prototype.hasUsername=function(){return null!==this.getUsername()};Note.prototype.getPrivateKey=function(){return this.getNoteField("Private Key")};Note.prototype.hasPrivateKey=function(){return null!==this.getPrivateKey()};Note.prototype.toString=function(){return Strings.Vault.SECURE_NOTE+": "+this._data.name};Note.prototype.getKeyValuePairs=function(){return function(a){var b=e.decryptMobile(this._data.extra,!0,this.getKey()),
c=new DialogInput.NestedFields;if(d(b.substring(9,b.indexOf("\n"))))for(var b=b.split("\n"),f,m={},g=0,k=b.length;g<k;++g){var q=b[g],u=q.indexOf(":");if(0<u){var p=q.substring(0,u);if(void 0===m[p]&&("object"!==typeof a||a[p])){c[p]=q.substring(u+1);f=p;m[p]=!0;continue}}f&&(c[f]+="\n"+q)}else c.Notes=b;return c}}();Note.prototype.getFormData=function(a){var b=VaultItem.prototype.getFormData.apply(this,arguments);b.extra=this.getKeyValuePairs(a.extra);b.notetype=this.getNoteType();b.template=this._data.template;
return b};Note.prototype.processEnteredData=function(a,b,d){AccountBase.prototype.processEnteredData.apply(this,arguments);var c;if(a.notetype!==this.NOTE_TYPES.GENERIC){c="NoteType:"+a.notetype;var h=a.extra,f;for(f in h)c+="\n"+f+":"+h[f]}else c=a.extra.Notes;a.extra=this.encryptIfNecessary("extra",c,d);this.getKey()!==d&&(a.attachkey=e.encrypt(e.decrypt(this._data.attachkey,this.getKey()),d));if(a.attacharraychanges&&a.attacharraychanges.add&&0<a.attacharraychanges.add.length){c=this.getAttachmentKey();
if(null===c)c=bg.SHA256(bg.lpCreatePass(32,1,1,1,1,1,1,1)),a.attachkey=e.encrypt(c,d),c=bg.AES.hex2bin(c);else if(!c)throw new AttachmentKeyException;h=0;for(f=a.attacharraychanges.add.length;h<f;++h){var l=a.attacharraychanges.add[h],g=this.getID();"0"!==g&&(l.id=g+"-"+l.id,l.parent=g);l.filename=e.encrypt(l.filename,c)}}};Note.prototype.getPostData=function(){return function(a){var b=AccountBase.prototype.getPostData.apply(this,arguments);b.url=bg.AES.url2hex(this._data.url);b.username="";b.password=
"";b.template=a.template;b.hexName=bg.AES.url2hex(a.name);b.notetype=a.notetype;a.attachkey&&(b.attachkey=a.attachkey);var c=b,d=a;if(d.attacharraychanges&&d.attacharraychanges.remove)for(var e=0,f=d.attacharraychanges.remove.length;e<f;++e)c["rmattach"+e]=d.attacharraychanges.remove[e];c=b;d=a;if(d.attacharraychanges&&d.attacharraychanges.add)for(e=0,f=d.attacharraychanges.add.length;e<f;++e){var g=d.attacharraychanges.add[e];c["filename"+e]=g.filename;c["mimetype"+e]=g.mimetype;c["attachid"+e]=
g.id.substring(g.id.indexOf("-")+1);c["attachbytes"+e]=g.bytes}return b}}();Note.prototype.update=function(){return function(a,b,d){AccountBase.prototype.update.apply(this,arguments);var c=d;if(c&&c.remove)for(var e=0,h=c.remove.length;e<h;++e)this.removeAttachment(c.remove[e]);if((c=d)&&c.add)for(e=0,h=c.add.length;e<h;++e)this.addAttachment(new Attachment(c.add[e]));a.attachpresent=0<this._attachments.length?"1":""}}();Note.prototype.add=function(a,b){(function(c,d){LPRequest.makeUpdateRequest(e.addNote,
{parameters:[c,a,b],success:function(b){c.update(b,a,d);c.publishAdd(Topics.NOTE_ADDED,a)}})})(this,this._data.attacharraychanges)};Note.prototype.save=function(a,b,d){(function(c,h){LPRequest.makeUpdateRequest(e.saveNote,{parameters:[c,a,b,d],success:function(){c.update(a,b,h);c.publishSuccess(Strings.Vault.SAVED)}})})(this,a.attacharraychanges)};Note.prototype.hasAttachments=function(){return 0<this._attachments.length};Note.prototype.getAttachments=function(){return this._attachments};Note.prototype.addAttachment=
function(a){a.setParentNote(this);this._attachments.push(a)};Note.prototype.removeAttachment=function(a){for(var b=0,c=this._attachments.length;b<c;++b)this._attachments[b]!==a&&this._attachments[b].getID()!==a||this._attachments.splice(b,1)}})();(function(){Attachment.prototype.setParentNote=function(a){if(this._parentNote=a)this._data.parent=a.getID()};Attachment.prototype.getID=function(){return this._data.id};Attachment.prototype.getName=function(){if(null===this._filename)if(null!==this._data.filename&&
this._data.filename.length){var a=this._parentNote?this._parentNote.getAttachmentKey():null;a&&(this._filename=e.decrypt(this._data.filename,a))}else{var a=this._data.mimetype,d="";0===a.indexOf("other:")?d="."+a.substring(6):0===a.indexOf("data:audio")?d="."+a.substring(11):0===a.indexOf("data:image")&&(d="."+a.substring(11));this._filename="attachment"+d}return this._filename?this._filename:this._data.filename};Attachment.prototype.getType=function(){return this._data.mimetype};Attachment.prototype.getBytes=
function(){return this._data.bytes};Attachment.prototype.handleClickEvent=function(a,d){switch(a){case Constants.ACTION_OPEN:this.open();break;case Constants.ACTION_SAVE:this.save();break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};var a=function(a){return function(){this._parentNote?a.apply(this,arguments):dialogs.alert.open({title:Strings.translateString("Error"),text:Strings.translateString("Attachment must be saved before it can be viewed.")})}};Attachment.prototype.open=
a(function(){e.openAttachment(this)});Attachment.prototype.save=a(function(){e.saveAttachment(this)});Attachment.prototype.deleteItem=function(){Topics.get(Topics.ATTACHMENT_REMOVED).publish(this);this.destroyViews()}})();(function(){FormFill.prototype.REPROMPT_TYPE="view_ff_prompt";FormFill.prototype.FORM_FILL_TYPE_GENERIC="0";FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD="1";FormFill.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};FormFill.prototype.getEditTopicID=function(){return Topics.EDIT_FORM_FILL};
FormFill.prototype.getName=function(){return this._data.decprofilename};FormFill.prototype.getID=function(){return this._data.ffid};FormFill.prototype.setID=function(a){this._data.ffid=a};FormFill.prototype.isCreditCard=function(){return this._data.profiletype===this.FORM_FILL_TYPE_CREDIT_CARD};FormFill.prototype.toString=function(){return Strings.Vault.FORM_FILL+": "+this._data.decprofilename};FormFill.prototype.handleClickEvent=function(a,d){switch(a){case Constants.ACTION_FILL:this.fill(d);break;
default:VaultItem.prototype.handleClickEvent.apply(this,arguments)}};FormFill.prototype.fill=function(a){e.fillProfile(this,a?a.source:"vault")};FormFill.prototype.deleteItem=function(a){this.passwordProtect(function(b){return function(){LPRequest.makeLockItemUpdateRequest(e.deleteFormFill,{parameters:[b,a],items:b,success:function(){b.deleteUpdates()},confirm:b.confirmDelete()})}}(this))};FormFill.prototype.enableCreditMonitoring=function(){LPRequest.makeUpdateRequest(e.createCreditMonitoringProfile,
{parameters:this})};FormFill.prototype.add=function(b,d){(function(b){LPRequest.makeUpdateRequest(e.addFormFill,{parameters:[b,d],success:function(a){b.update(a);b._data.creditmon&&b.enableCreditMonitoring();b.publishAdd(Topics.FORM_FILL_ADDED)},confirm:b._data.creditmon?a(b._data,b.getKey()):null})})(this)};var a=function(){var a=function(a,b,e){var c=g.createElement("tr","settingsRow");c.appendChild(g.createElement("td","settingLabel",b));"string"===typeof e?c.appendChild(g.createElement("td",null,
e)):(b=g.createElement("td"),b.appendChild(e),c.appendChild(b));a.appendChild(c)};return function(b,c){var d=[Strings.translateString("Only the below information will be sent to LastPass."),Strings.translateString("Other confidential Form Fill information, such as credit card numbers, will not be sent.")],f=g.createElement("table","settings creditMonConfirm");a(f,Strings.translateString("Name"),e.decryptMobile(b.firstname,!0,c)+" "+e.decryptMobile(b.lastname,!0,c));a(f,Strings.translateString("Birthday"),
e.decryptMobile(b.birthday,!0,c));a(f,Strings.translateString("Social Security Number"),"\u2022\u2022\u2022\u2022 "+e.decryptMobile(b.ssn,!0,c).slice(-4));var k=Strings.translateString("Phone Number"),m;m=e.decryptMobile(b.phone,!0,c);11===m.length&&(m=m.substring(1));m="("+m.substring(0,3)+") "+m.substring(3,6)+"-"+m.substring(6);a(f,k,m);k=Strings.translateString("Address");m=g.createElement("div");b.address1&&m.appendChild(g.createElement("p",null,e.decryptMobile(b.address1,!0,c)));b.address2&&
m.appendChild(g.createElement("p",null,e.decryptMobile(b.address2,!0,c)));b.address3&&m.appendChild(g.createElement("p",null,e.decryptMobile(b.address3,!0,c)));m.appendChild(g.createElement("p",null,e.decryptMobile(b.city,!0,c)+", "+e.decryptMobile(b.state,!0,c)+" "+e.decryptMobile(b.zip,!0,c)));a(f,k,m);g.addZebraStriping(f);d.push(f);f=g.createElement("p",{compoundtranslation:!0,"class":"dialogText"},"I have read and agree with the ");f.appendChild(g.createElement("a",{target:"_blank",href:e.getBaseURL()+
"creditmonitoring.php?cmd=showterms"},"LastPass Terms and Conditions"));Strings.translate(f);d.push(f);return{title:Strings.Vault.ADD_CREDIT_MON,text:d,nextButtonText:Strings.translateString("I Agree"),backButtonText:Strings.translateString("I Do Not Agree")}}}();FormFill.prototype.save=function(b,d,c){(function(d){LPRequest.makeUpdateRequest(e.saveFormFill,{parameters:[d,b,c],success:function(){d.update(b);d.publishSuccess(Strings.Vault.SAVED)},confirm:b.creditmon&&!d._data.creditmon?a(b,d.getKey()):
null})})(this)};FormFill.prototype.update=function(a){var b=!1;a.creditmon&&!this._data.creditmon&&(b=!0);VaultItem.prototype.update.apply(this,arguments);b&&this.enableCreditMonitoring()};FormFill.prototype.getPostData=function(a){var b=VaultItem.prototype.getPostData.apply(this,arguments),c=this.getKey(),f;for(f in a){var g=a[f];if(this.isEncryptedField(f))b[f]=e.encryptWithKey(e.decryptMobile(g,!0,c),c);else switch(f){case "creditmon":case "pwprotect":break;default:b[f]=g}}b.ffid=this.getID();
"undefined"!==typeof b.custom_fields&&delete b.custom_fields;a.creditmon&&(b.creditmon="on");return b};FormFill.prototype.isEncryptedField=function(a){if(-1!==a.indexOf("cfid"))return!1;switch(a){case "decprofilename":case "pwprotect":case "creditmon":case "custom_fields":case "profiletype":return!1;default:return!0}};FormFill.prototype.processEnteredData=function(a,d,c){for(var b in a)if(d=a[b],"custom_fields"===b)for(var f=0,g=d.length;f<g;++f){var k=d[f],t="customfield"+(f+1);a[t+"cfid"]=k.cfid;
a[t+"text"]=e.encryptMobile(k.text,!0,c);a[t+"value"]=e.encryptMobile(k.value,!0,c);a[t+"alttext"]=""}else this.isEncryptedField(b)&&(a[b]=this.encryptIfNecessary(b,a[b],c));delete a.custom_fields;a.profilename=e.encryptMobile(a.decprofilename,!0,c)};FormFill.prototype.getFormData=function(a){var b={},c=this.getKey(),f;for(f in a)this.isEncryptedField(f)?b[f]=e.decryptMobile(this._data[f],!0,c):b[f]=this._data[f];if(a.custom_fields)for(b.custom_fields=[],a=0,f=this._data.custom_fields.length;a<f;++a){var g=
this._data.custom_fields[a],k={};k.cfid=g.cfid;k.text=e.decryptMobile(g.text,!0,c);k.value=e.decryptMobile(g.value,!0,c);g=e.decryptMobile(g.alttext,!0,c);""!==g&&(k.value+="\n"+g);b.custom_fields.push(k)}return b}})();(function(){Identity.prototype.REPROMPT_TYPE="switch_identity_prompt";Identity.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Identity.prototype.getName=function(){return this._data.deciname};Identity.prototype.getID=function(){return this._data.iid};Identity.prototype.setID=
function(a){this._data.iid=a};Identity.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_ENABLE:this.enable();break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};Identity.prototype.getEditTopicID=function(a){return Topics.EDIT_IDENTITY};Identity.prototype.enable=function(){var a=function(){Topics.get(Topics.IDENTITY_ENABLE).publish(this);this._enabled=!0;this.updateViews()};return function(b){g.getOption(b,"reprompt",!0)?this.passwordProtect(function(){a.apply(this);
b&&b.callback&&b.callback()}):a.apply(this)}}();Identity.prototype.disable=function(){this._enabled=!1;this.updateViews()};Identity.prototype.processEnteredData=function(a,b,d){a.iname=e.encryptAES(a.deciname,d)};Identity.prototype.save=function(){var a=function(a){this.update(a);this.publishSuccess(Strings.Vault.SAVED)};return function(b){LPRequest.makeUpdateRequest(e.saveIdentity,{params:{identity:b},success:this.createHandler(a)})}}();Identity.prototype.add=function(){var a=function(a){this.update(a);
this.publishAdd(Topics.IDENTITY_ADDED)};return function(){LPRequest.makeUpdateRequest(e.addIdentity,{params:{identity:this._data},success:this.createHandler(a)})}}();Identity.prototype.deleteItem=function(){var a=function(){this.deleteUpdates()},b=function(){e.logEvent("v_did");LPRequest.makeLockItemUpdateRequest(e.deleteIdentity,{params:{id:this.getID()},items:this,success:this.createHandler(a),confirm:this.confirmDelete()})};return function(){this._enabled?Topics.get(Topics.ERROR).publish(Strings.translateString("%1 cannot be deleted while enabled.",
this.toString())):this.passwordProtect(b)}}();Identity.prototype.toString=function(){return Strings.Vault.IDENTITY+": "+this.getName()}})()})($,document,LPTools,LPProxy);
